//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 09:18:04 PM EET 
//


package ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SignatureDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SigantureDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="SignatureTime" type="{http://www.w3.org/2001/XMLSchema}time"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureDataType", propOrder = {
    "sigantureDate",
    "signatureTime"
})
public class SignatureDataType {

    @XmlElement(name = "SigantureDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar sigantureDate;
    @XmlElement(name = "SignatureTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar signatureTime;

    /**
     * Gets the value of the sigantureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSigantureDate() {
        return sigantureDate;
    }

    /**
     * Sets the value of the sigantureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSigantureDate(XMLGregorianCalendar value) {
        this.sigantureDate = value;
    }

    /**
     * Gets the value of the signatureTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSignatureTime() {
        return signatureTime;
    }

    /**
     * Sets the value of the signatureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSignatureTime(XMLGregorianCalendar value) {
        this.signatureTime = value;
    }

}
