//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.eu.x_road.dhx.producer;

import org.w3c.dom.Element;

import java.util.ArrayList;
import java.util.List;

import javax.activation.DataHandler;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttachmentRef;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DHXVersion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="recipient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="recipientSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="consignmentId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="documentAttachment" type="{http://ws-i.org/profiles/basic/1.1/xsd}swaRef"/&gt;
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dhxVersion",
    "recipient",
    "recipientSystem",
    "consignmentId",
    "documentAttachment",
    "any"
})
@XmlRootElement(name = "sendDocument")
public class SendDocument {

  @XmlElement(name = "DHXVersion", required = true)
  protected String dhxVersion;
  protected String recipient;
  protected String recipientSystem;
  @XmlElement(required = true)
  protected String consignmentId;
  @XmlElement(required = true, type = String.class)
  @XmlAttachmentRef
  @XmlSchemaType(name = "anyURI")
  protected DataHandler documentAttachment;
  @XmlAnyElement
  protected List<Element> any;

  /**
   * Gets the value of the dhxVersion property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDHXVersion() {
    return dhxVersion;
  }

  /**
   * Sets the value of the dhxVersion property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDHXVersion(String value) {
    this.dhxVersion = value;
  }

  /**
   * Gets the value of the recipient property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRecipient() {
    return recipient;
  }

  /**
   * Sets the value of the recipient property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRecipient(String value) {
    this.recipient = value;
  }

  /**
   * Gets the value of the recipientSystem property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRecipientSystem() {
    return recipientSystem;
  }

  /**
   * Sets the value of the recipientSystem property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRecipientSystem(String value) {
    this.recipientSystem = value;
  }

  /**
   * Gets the value of the consignmentId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getConsignmentId() {
    return consignmentId;
  }

  /**
   * Sets the value of the consignmentId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setConsignmentId(String value) {
    this.consignmentId = value;
  }

  /**
   * Gets the value of the documentAttachment property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public DataHandler getDocumentAttachment() {
    return documentAttachment;
  }

  /**
   * Sets the value of the documentAttachment property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDocumentAttachment(DataHandler value) {
    this.documentAttachment = value;
  }

  /**
   * Gets the value of the any property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the any property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getAny().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Element }
   * 
   * 
   */
  public List<Element> getAny() {
    if (any == null) {
      any = new ArrayList<Element>();
    }
    return this.any;
  }

}
