//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.eu.x_road.dhx.producer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fault" type="{http://dhx.x-road.eu/producer}fault" minOccurs="0"/&gt;
 *         &lt;element name="receiptId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fault",
    "receiptId"
})
@XmlRootElement(name = "sendDocumentResponse")
public class SendDocumentResponse {

  protected Fault fault;
  @XmlElement(required = true)
  protected String receiptId;

  /**
   * Gets the value of the fault property.
   * 
   * @return possible object is {@link Fault }
   * 
   */
  public Fault getFault() {
    return fault;
  }

  /**
   * Sets the value of the fault property.
   * 
   * @param value allowed object is {@link Fault }
   * 
   */
  public void setFault(Fault value) {
    this.fault = value;
  }

  /**
   * Gets the value of the receiptId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReceiptId() {
    return receiptId;
  }

  /**
   * Sets the value of the receiptId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setReceiptId(String value) {
    this.receiptId = value;
  }

}
