//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import ee.ria.dhx.server.types.ee.riik.schemas.dhl.DhlDokumentType;
import ee.ria.dhx.types.ee.riik.schemas.deccontainer.vers_2_1.DecContainer;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for documentsArrayType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentsArrayType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dokument" type="{http://www.riik.ee/schemas/dhl}dhlDokumentType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentsArrayType", propOrder = {
    "DecContainer"
})
@XmlSeeAlso({
    ReceiveDocumentsV4ResponseTypeUnencoded.class
})
@XmlRootElement(name = "DocWrapper")
public class DocumentsArrayType {

  // @XmlElementWrapper(name="docs")
   @XmlElement(namespace="http://www.riik.ee/schemas/deccontainer/vers_2_1/")
  protected List<DecContainer> DecContainer;

  /**
   * Gets the value of the dokument property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the dokument property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getDokument().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link DhlDokumentType }
   * 
   * @return List of {@link DecContainer}
   */
  public List<DecContainer> getDecContainer() {
    if (DecContainer == null) {
      DecContainer = new ArrayList<DecContainer>();
    }
    return this.DecContainer;
  }
  /*
   * public List<DecContainer> getDokument() { if (dokument == null) { dokument = new
   * ArrayList<DecContainer>(); } return this.dokument; }
   */

}
