//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Tagasiside vastuvõetud dokumendi oleku ja vigade kohta
 * 
 * <p>
 * Java class for tagasisideType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tagasisideType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="dhl_id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="vastuvotja_staatus_id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}fault" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dokumendid", propOrder = {

})
@XmlRootElement(name = "dokumendid", namespace = "")
public class Dokumendid {

  @XmlAttribute(name = "href")
  @XmlSchemaType(name = "anyURI")
  protected String hrefString;



  /**
   * Returns the hrefString.
   *
   * @return the hrefString
   */
  public String getHrefString() {
    return hrefString;
  }

  /**
   * Sets the hrefString.
   *
   * @param hrefString the hrefString to set
   */
  public void setHrefString(String hrefString) {
    this.hrefString = hrefString;
  }

  @XmlElement(name = "item")
  @XmlSchemaType(name = "anyURI")
  protected List<TagasisideType> tagasisided;

  /**
   * Returns the tagasisided.
   *
   * @return the tagasisided
   */
  public List<TagasisideType> getTagasisided() {
    return tagasisided;
  }

  /**
   * Sets the tagasisided.
   *
   * @param tagasisided the tagasisided to set
   */
  public void setTagasisided(List<TagasisideType> tagasisided) {
    this.tagasisided = tagasisided;
  }
}
