//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import ee.ria.dhx.server.types.ee.riik.schemas.dhl.Edastus;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for getSendStatusV2ResponseTypeUnencoded complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getSendStatusV2ResponseTypeUnencoded"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.riik.ee/schemas/dhl-meta-automatic}dhl_id"/&gt;
 *                   &lt;element ref="{http://www.riik.ee/schemas/dhl}edastus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="staatuse_ajalugu" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}statusHistoryType"/&gt;
 *                   &lt;element name="olek" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSendStatusV2ResponseTypeUnencoded", propOrder = {
    "item"
})
public class GetSendStatusV2ResponseTypeUnencoded {

  @XmlElement(required = true)
  protected List<GetSendStatusV2ResponseTypeUnencoded.Item> item;

  /**
   * Gets the value of the item property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the item property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getItem().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link GetSendStatusV2ResponseTypeUnencoded.Item }
   * 
   * 
   */
  public List<GetSendStatusV2ResponseTypeUnencoded.Item> getItem() {
    if (item == null) {
      item = new ArrayList<GetSendStatusV2ResponseTypeUnencoded.Item>();
    }
    return this.item;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.riik.ee/schemas/dhl-meta-automatic}dhl_id"/&gt;
     *         &lt;element ref="{http://www.riik.ee/schemas/dhl}edastus" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="staatuse_ajalugu" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}statusHistoryType"/&gt;
     *         &lt;element name="olek" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "dhlId",
      "edastus",
      "staatuseAjalugu",
      "olek"
  })
  @XmlRootElement(name = "item")
  public static class Item {

    @XmlElement(name = "dhl_id", namespace = "http://www.riik.ee/schemas/dhl-meta-automatic", required = true)
    protected String dhlId;
    @XmlElement(namespace = "http://www.riik.ee/schemas/dhl")
    protected List<Edastus> edastus;
    @XmlElement(name = "staatuse_ajalugu", required = true)
    protected StatusHistoryType staatuseAjalugu;
    @XmlElement(required = true)
    protected String olek;

    /**
     * Gets the value of the dhlId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDhlId() {
      return dhlId;
    }

    /**
     * Sets the value of the dhlId property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDhlId(String value) {
      this.dhlId = value;
    }

    /**
     * Gets the value of the edastus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the edastus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
         *    getEdastus().add(newItem);
         * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Edastus }
     * 
     * 
     */
    public List<Edastus> getEdastus() {
      if (edastus == null) {
        edastus = new ArrayList<Edastus>();
      }
      return this.edastus;
    }

    /**
     * Gets the value of the staatuseAjalugu property.
     * 
     * @return possible object is {@link StatusHistoryType }
     * 
     */
    public StatusHistoryType getStaatuseAjalugu() {
      return staatuseAjalugu;
    }

    /**
     * Sets the value of the staatuseAjalugu property.
     * 
     * @param value allowed object is {@link StatusHistoryType }
     * 
     */
    public void setStaatuseAjalugu(StatusHistoryType value) {
      this.staatuseAjalugu = value;
    }

    /**
     * Gets the value of the olek property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOlek() {
      return olek;
    }

    /**
     * Sets the value of the olek property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setOlek(String value) {
      this.olek = value;
    }

  }

}
