//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:49:24 AM EET 
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getSendStatusV2RequestTypeUnencoded complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getSendStatusV2RequestTypeUnencoded"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="item" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="dhl_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="dokument_guid" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}GUID"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="staatuse_ajalugu" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSendStatusV2RequestTypeUnencoded", propOrder = {
    "item",
    "staatuseAjalugu"
})
public class GetSendStatusV2RequestTypeUnencoded {

    @XmlElement(required = true)
    protected List<GetSendStatusV2RequestTypeUnencoded.Item> item;
    @XmlElement(name = "staatuse_ajalugu")
    protected boolean staatuseAjalugu;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetSendStatusV2RequestTypeUnencoded.Item }
     * 
     * 
     */
    public List<GetSendStatusV2RequestTypeUnencoded.Item> getItem() {
        if (item == null) {
            item = new ArrayList<GetSendStatusV2RequestTypeUnencoded.Item>();
        }
        return this.item;
    }

    /**
     * Gets the value of the staatuseAjalugu property.
     * 
     */
    public boolean isStaatuseAjalugu() {
        return staatuseAjalugu;
    }

    /**
     * Sets the value of the staatuseAjalugu property.
     * 
     */
    public void setStaatuseAjalugu(boolean value) {
        this.staatuseAjalugu = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="dhl_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dokument_guid" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}GUID"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dhlId",
        "dokumentGuid"
    })
    public static class Item {

        @XmlElement(name = "dhl_id")
        protected String dhlId;
        @XmlElement(name = "dokument_guid")
        protected String dokumentGuid;

        /**
         * Gets the value of the dhlId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDhlId() {
            return dhlId;
        }

        /**
         * Sets the value of the dhlId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDhlId(String value) {
            this.dhlId = value;
        }

        /**
         * Gets the value of the dokumentGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDokumentGuid() {
            return dokumentGuid;
        }

        /**
         * Sets the value of the dokumentGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDokumentGuid(String value) {
            this.dokumentGuid = value;
        }

    }

}
