//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for institutionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="institutionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="regnr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nimi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="saatmine" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}sendingOptionArrayType"/&gt;
 *         &lt;element name="ks_asutuse_regnr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "institutionType", propOrder = {
    "regnr",
    "nimi",
    "saatmine",
    "ksAsutuseRegnr"
})
public class InstitutionType {

  @XmlElement(required = true)
  protected String regnr;
  @XmlElement(required = true)
  protected String nimi;
  @XmlElement(required = true)
  protected SendingOptionArrayType saatmine;
  @XmlElement(name = "ks_asutuse_regnr")
  protected String ksAsutuseRegnr;

  /**
   * Gets the value of the regnr property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRegnr() {
    return regnr;
  }

  /**
   * Sets the value of the regnr property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRegnr(String value) {
    this.regnr = value;
  }

  /**
   * Gets the value of the nimi property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getNimi() {
    return nimi;
  }

  /**
   * Sets the value of the nimi property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setNimi(String value) {
    this.nimi = value;
  }

  /**
   * Gets the value of the saatmine property.
   * 
   * @return possible object is {@link SendingOptionArrayType }
   * 
   */
  public SendingOptionArrayType getSaatmine() {
    return saatmine;
  }

  /**
   * Sets the value of the saatmine property.
   * 
   * @param value allowed object is {@link SendingOptionArrayType }
   * 
   */
  public void setSaatmine(SendingOptionArrayType value) {
    this.saatmine = value;
  }

  /**
   * Gets the value of the ksAsutuseRegnr property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getKsAsutuseRegnr() {
    return ksAsutuseRegnr;
  }

  /**
   * Sets the value of the ksAsutuseRegnr property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setKsAsutuseRegnr(String value) {
    this.ksAsutuseRegnr = value;
  }

}
