//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for markDocumentsReceivedV3RequestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="markDocumentsReceivedV3RequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kaust" type="{http://www.riik.ee/schemas/dhl-meta-automatic}dhlDokTaisnimiType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "markDocumentsReceivedV3RequestType", propOrder = {
    "kaust", "dokumendid"
})
public class MarkDocumentsReceivedV3RequestType {

  protected String kaust;


  @XmlElement(name = "dokumendid")
  Dokumendid dokumendid;

  /*
   * @XmlElementWrapper(name = "dokumendid")
   * 
   * @XmlElement(name = "item") protected List<TagasisideType> dokumendid;
   */


  /*
   * public List<TagasisideType> getDokumendid() { return dokumendid; }
   * 
   * public void setDokumendid(List<TagasisideType> dokumendid) { this.dokumendid = dokumendid; }
   */

  /**
   * Returns the dokumendid.
   *
   * @return the dokumendid
   */
  public Dokumendid getDokumendid() {
    return dokumendid;
  }

  /**
   * Sets the dokumendid.
   *
   * @param dokumendid the dokumendid to set
   */
  public void setDokumendid(Dokumendid dokumendid) {
    this.dokumendid = dokumendid;
  }

  /**
   * Gets the value of the kaust property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getKaust() {
    return kaust;
  }

  /**
   * Sets the value of the kaust property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setKaust(String value) {
    this.kaust = value;
  }

}
