//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:49:24 AM EET 
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for receiveDocumentsV4RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="receiveDocumentsV4RequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="arv" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="allyksuse_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ametikoha_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="kaust" type="{http://www.riik.ee/schemas/dhl-meta-automatic}dhlDokTaisnimiType" minOccurs="0"/&gt;
 *         &lt;element name="edastus_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fragment_nr" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="fragmendi_suurus_baitides" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "receiveDocumentsV4RequestType", propOrder = {
    "arv",
    "allyksuseLyhinimetus",
    "ametikohaLyhinimetus",
    "kaust",
    "edastusId",
    "fragmentNr",
    "fragmendiSuurusBaitides"
})
public class ReceiveDocumentsV4RequestType {

    protected BigInteger arv;
    @XmlElement(name = "allyksuse_lyhinimetus")
    protected String allyksuseLyhinimetus;
    @XmlElement(name = "ametikoha_lyhinimetus")
    protected String ametikohaLyhinimetus;
    protected String kaust;
    @XmlElement(name = "edastus_id")
    protected String edastusId;
    @XmlElement(name = "fragment_nr")
    protected BigInteger fragmentNr;
    @XmlElement(name = "fragmendi_suurus_baitides")
    protected Long fragmendiSuurusBaitides;

    /**
     * Gets the value of the arv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArv() {
        return arv;
    }

    /**
     * Sets the value of the arv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArv(BigInteger value) {
        this.arv = value;
    }

    /**
     * Gets the value of the allyksuseLyhinimetus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllyksuseLyhinimetus() {
        return allyksuseLyhinimetus;
    }

    /**
     * Sets the value of the allyksuseLyhinimetus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllyksuseLyhinimetus(String value) {
        this.allyksuseLyhinimetus = value;
    }

    /**
     * Gets the value of the ametikohaLyhinimetus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmetikohaLyhinimetus() {
        return ametikohaLyhinimetus;
    }

    /**
     * Sets the value of the ametikohaLyhinimetus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmetikohaLyhinimetus(String value) {
        this.ametikohaLyhinimetus = value;
    }

    /**
     * Gets the value of the kaust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKaust() {
        return kaust;
    }

    /**
     * Sets the value of the kaust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKaust(String value) {
        this.kaust = value;
    }

    /**
     * Gets the value of the edastusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEdastusId() {
        return edastusId;
    }

    /**
     * Sets the value of the edastusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEdastusId(String value) {
        this.edastusId = value;
    }

    /**
     * Gets the value of the fragmentNr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFragmentNr() {
        return fragmentNr;
    }

    /**
     * Sets the value of the fragmentNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFragmentNr(BigInteger value) {
        this.fragmentNr = value;
    }

    /**
     * Gets the value of the fragmendiSuurusBaitides property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFragmendiSuurusBaitides() {
        return fragmendiSuurusBaitides;
    }

    /**
     * Sets the value of the fragmendiSuurusBaitides property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFragmendiSuurusBaitides(Long value) {
        this.fragmendiSuurusBaitides = value;
    }

}
