//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:49:24 AM EET 
//


package ee.ria.dhx.server.types.ee.riik.xrd.dhl.producers.producer.dhl;

import java.math.BigInteger;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ee.ria.dhx.server.types.ee.riik.schemas.dhl.Fault;
import ee.ria.dhx.server.types.ee.riik.schemas.dhl.Metaxml;


/**
 * <p>Java class for statusHistoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statusHistoryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="saaja"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;all&gt;
 *                             &lt;element ref="{http://www.riik.ee/schemas/dhl}regnr" minOccurs="0"/&gt;
 *                             &lt;element ref="{http://www.riik.ee/schemas/dhl}isikukood" minOccurs="0"/&gt;
 *                             &lt;element name="allyksuse_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ametikoha_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/all&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="staatuse_ajalugu_id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="staatuse_muutmise_aeg" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="staatus" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}statusType"/&gt;
 *                   &lt;element name="vastuvotja_staatus_id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element ref="{http://www.riik.ee/schemas/dhl}metaxml" minOccurs="0"/&gt;
 *                   &lt;element ref="{http://www.riik.ee/schemas/dhl}fault" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statusHistoryType", propOrder = {
    "status"
})
public class StatusHistoryType {

    @XmlElement(required = true)
    protected List<StatusHistoryType.Status> status;

    /**
     * Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusHistoryType.Status }
     * 
     * 
     */
    public List<StatusHistoryType.Status> getStatus() {
        if (status == null) {
            status = new ArrayList<StatusHistoryType.Status>();
        }
        return this.status;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="saaja"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;all&gt;
     *                   &lt;element ref="{http://www.riik.ee/schemas/dhl}regnr" minOccurs="0"/&gt;
     *                   &lt;element ref="{http://www.riik.ee/schemas/dhl}isikukood" minOccurs="0"/&gt;
     *                   &lt;element name="allyksuse_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ametikoha_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/all&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="staatuse_ajalugu_id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="staatuse_muutmise_aeg" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="staatus" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}statusType"/&gt;
     *         &lt;element name="vastuvotja_staatus_id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element ref="{http://www.riik.ee/schemas/dhl}metaxml" minOccurs="0"/&gt;
     *         &lt;element ref="{http://www.riik.ee/schemas/dhl}fault" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saaja",
        "staatuseAjaluguId",
        "staatuseMuutmiseAeg",
        "staatus",
        "vastuvotjaStaatusId",
        "metaxml",
        "fault"
    })
    public static class Status {

        @XmlElement(required = true)
        protected StatusHistoryType.Status.Saaja saaja;
        @XmlElement(name = "staatuse_ajalugu_id", required = true)
        protected BigInteger staatuseAjaluguId;
        @XmlElement(name = "staatuse_muutmise_aeg", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar staatuseMuutmiseAeg;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected StatusType staatus;
        @XmlElement(name = "vastuvotja_staatus_id", required = true)
        protected BigInteger vastuvotjaStaatusId;
        @XmlElement(namespace = "http://www.riik.ee/schemas/dhl")
        protected Metaxml metaxml;
        @XmlElement(namespace = "http://www.riik.ee/schemas/dhl")
        protected Fault fault;

        /**
         * Gets the value of the saaja property.
         * 
         * @return
         *     possible object is
         *     {@link StatusHistoryType.Status.Saaja }
         *     
         */
        public StatusHistoryType.Status.Saaja getSaaja() {
            return saaja;
        }

        /**
         * Sets the value of the saaja property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusHistoryType.Status.Saaja }
         *     
         */
        public void setSaaja(StatusHistoryType.Status.Saaja value) {
            this.saaja = value;
        }

        /**
         * Gets the value of the staatuseAjaluguId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getStaatuseAjaluguId() {
            return staatuseAjaluguId;
        }

        /**
         * Sets the value of the staatuseAjaluguId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setStaatuseAjaluguId(BigInteger value) {
            this.staatuseAjaluguId = value;
        }

        /**
         * Gets the value of the staatuseMuutmiseAeg property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStaatuseMuutmiseAeg() {
            return staatuseMuutmiseAeg;
        }

        /**
         * Sets the value of the staatuseMuutmiseAeg property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStaatuseMuutmiseAeg(XMLGregorianCalendar value) {
            this.staatuseMuutmiseAeg = value;
        }

        /**
         * Gets the value of the staatus property.
         * 
         * @return
         *     possible object is
         *     {@link StatusType }
         *     
         */
        public StatusType getStaatus() {
            return staatus;
        }

        /**
         * Sets the value of the staatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusType }
         *     
         */
        public void setStaatus(StatusType value) {
            this.staatus = value;
        }

        /**
         * Gets the value of the vastuvotjaStaatusId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVastuvotjaStaatusId() {
            return vastuvotjaStaatusId;
        }

        /**
         * Sets the value of the vastuvotjaStaatusId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVastuvotjaStaatusId(BigInteger value) {
            this.vastuvotjaStaatusId = value;
        }

        /**
         * Gets the value of the metaxml property.
         * 
         * @return
         *     possible object is
         *     {@link Metaxml }
         *     
         */
        public Metaxml getMetaxml() {
            return metaxml;
        }

        /**
         * Sets the value of the metaxml property.
         * 
         * @param value
         *     allowed object is
         *     {@link Metaxml }
         *     
         */
        public void setMetaxml(Metaxml value) {
            this.metaxml = value;
        }

        /**
         * Gets the value of the fault property.
         * 
         * @return
         *     possible object is
         *     {@link Fault }
         *     
         */
        public Fault getFault() {
            return fault;
        }

        /**
         * Sets the value of the fault property.
         * 
         * @param value
         *     allowed object is
         *     {@link Fault }
         *     
         */
        public void setFault(Fault value) {
            this.fault = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;all&gt;
         *         &lt;element ref="{http://www.riik.ee/schemas/dhl}regnr" minOccurs="0"/&gt;
         *         &lt;element ref="{http://www.riik.ee/schemas/dhl}isikukood" minOccurs="0"/&gt;
         *         &lt;element name="allyksuse_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ametikoha_lyhinimetus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/all&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Saaja {

            @XmlElement(namespace = "http://www.riik.ee/schemas/dhl")
            protected String regnr;
            @XmlElement(namespace = "http://www.riik.ee/schemas/dhl")
            protected String isikukood;
            @XmlElement(name = "allyksuse_lyhinimetus")
            protected String allyksuseLyhinimetus;
            @XmlElement(name = "ametikoha_lyhinimetus")
            protected String ametikohaLyhinimetus;

            /**
             * Gets the value of the regnr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegnr() {
                return regnr;
            }

            /**
             * Sets the value of the regnr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegnr(String value) {
                this.regnr = value;
            }

            /**
             * Gets the value of the isikukood property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsikukood() {
                return isikukood;
            }

            /**
             * Sets the value of the isikukood property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsikukood(String value) {
                this.isikukood = value;
            }

            /**
             * Gets the value of the allyksuseLyhinimetus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAllyksuseLyhinimetus() {
                return allyksuseLyhinimetus;
            }

            /**
             * Sets the value of the allyksuseLyhinimetus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAllyksuseLyhinimetus(String value) {
                this.allyksuseLyhinimetus = value;
            }

            /**
             * Gets the value of the ametikohaLyhinimetus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAmetikohaLyhinimetus() {
                return ametikohaLyhinimetus;
            }

            /**
             * Sets the value of the ametikohaLyhinimetus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAmetikohaLyhinimetus(String value) {
                this.ametikohaLyhinimetus = value;
            }

        }

    }

}
