//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://x-road.eu/xsd/representation.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ee.ria.dhx.types.eu.x_road.xsd.representation;

