//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.ee.riik.schemas.deccontainer.vers_2_1;

import ee.ria.dhx.bigdata.annotation.BigDataXmlElement;

import org.w3c.dom.Element;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Transport"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DecSender"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PersonalIdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="DecRecipient" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="PersonalIdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Initiator" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="InitiatorRecordOriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="InitiatorRecordDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
 *                   &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
 *                   &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RecordCreator" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
 *                   &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
 *                   &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RecordSenderToDec" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
 *                   &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
 *                   &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Recipient" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RecipientRecordGuid" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}GuidType" minOccurs="0"/&gt;
 *                   &lt;element name="RecipientRecordOriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="MessageForRecipient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
 *                   &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
 *                   &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RecordMetadata"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RecordGuid" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}GuidType"/&gt;
 *                   &lt;element name="RecordType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RecordOriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RecordDateRegistered" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="RecordTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RecordLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RecordAbstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ReplyDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Access"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AccessConditionsCode" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}AccessConditionType"/&gt;
 *                   &lt;element name="AccessRestriction" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="RestrictionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="RestrictionBeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="RestrictionEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="RestrictionEndEvent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="RestrictionInvalidSince" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                             &lt;element name="RestrictionBasis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="InformationOwner" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SignatureMetadata" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SignatureType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Signer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Verified" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SignatureVerificationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="File" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="FileGuid" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}GuidType"/&gt;
 *                   &lt;element name="RecordMainComponent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="MimeType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FileSize" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *                   &lt;element name="ZipBase64Content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RecordTypeSpecificMetadata" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DecMetadata"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="DecId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="DecFolder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DecReceiptDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transport",
    "initiator",
    "recordCreator",
    "recordSenderToDec",
    "recipient",
    "recordMetadata",
    "access",
    "signatureMetadata",
    "file",
    "recordTypeSpecificMetadata",
    "decMetadata"
})
@XmlRootElement(name = "DecContainer")
public class DecContainer {

  @XmlElement(name = "Transport", required = true)
  protected DecContainer.Transport transport;
  @XmlElement(name = "Initiator")
  protected DecContainer.Initiator initiator;
  @XmlElement(name = "RecordCreator")
  protected DecContainer.RecordCreator recordCreator;
  @XmlElement(name = "RecordSenderToDec")
  protected DecContainer.RecordSenderToDec recordSenderToDec;
  @XmlElement(name = "Recipient", required = true)
  protected List<DecContainer.Recipient> recipient;
  @XmlElement(name = "RecordMetadata", required = true)
  protected DecContainer.RecordMetadata recordMetadata;
  @XmlElement(name = "Access", required = true)
  protected DecContainer.Access access;
  @XmlElement(name = "SignatureMetadata")
  protected List<DecContainer.SignatureMetadata> signatureMetadata;
  @XmlElement(name = "File", required = true)
  protected List<DecContainer.File> file;
  @XmlElement(name = "RecordTypeSpecificMetadata")
  protected DecContainer.RecordTypeSpecificMetadata recordTypeSpecificMetadata;
  @XmlElement(name = "DecMetadata", required = true)
  protected DecContainer.DecMetadata decMetadata;

  /**
   * Gets the value of the transport property.
   * 
   * @return possible object is {@link DecContainer.Transport }
   * 
   */
  public DecContainer.Transport getTransport() {
    return transport;
  }

  /**
   * Sets the value of the transport property.
   * 
   * @param value allowed object is {@link DecContainer.Transport }
   * 
   */
  public void setTransport(DecContainer.Transport value) {
    this.transport = value;
  }

  /**
   * Gets the value of the initiator property.
   * 
   * @return possible object is {@link DecContainer.Initiator }
   * 
   */
  public DecContainer.Initiator getInitiator() {
    return initiator;
  }

  /**
   * Sets the value of the initiator property.
   * 
   * @param value allowed object is {@link DecContainer.Initiator }
   * 
   */
  public void setInitiator(DecContainer.Initiator value) {
    this.initiator = value;
  }

  /**
   * Gets the value of the recordCreator property.
   * 
   * @return possible object is {@link DecContainer.RecordCreator }
   * 
   */
  public DecContainer.RecordCreator getRecordCreator() {
    return recordCreator;
  }

  /**
   * Sets the value of the recordCreator property.
   * 
   * @param value allowed object is {@link DecContainer.RecordCreator }
   * 
   */
  public void setRecordCreator(DecContainer.RecordCreator value) {
    this.recordCreator = value;
  }

  /**
   * Gets the value of the recordSenderToDec property.
   * 
   * @return possible object is {@link DecContainer.RecordSenderToDec }
   * 
   */
  public DecContainer.RecordSenderToDec getRecordSenderToDec() {
    return recordSenderToDec;
  }

  /**
   * Sets the value of the recordSenderToDec property.
   * 
   * @param value allowed object is {@link DecContainer.RecordSenderToDec }
   * 
   */
  public void setRecordSenderToDec(DecContainer.RecordSenderToDec value) {
    this.recordSenderToDec = value;
  }

  /**
   * Gets the value of the recipient property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the recipient property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getRecipient().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link DecContainer.Recipient }
   * 
   * @return list of {@link Recipient}
   */
  public List<DecContainer.Recipient> getRecipient() {
    if (recipient == null) {
      recipient = new ArrayList<DecContainer.Recipient>();
    }
    return this.recipient;
  }

  /**
   * Gets the value of the recordMetadata property.
   * 
   * @return possible object is {@link DecContainer.RecordMetadata }
   * 
   */
  public DecContainer.RecordMetadata getRecordMetadata() {
    return recordMetadata;
  }

  /**
   * Sets the value of the recordMetadata property.
   * 
   * @param value allowed object is {@link DecContainer.RecordMetadata }
   * 
   */
  public void setRecordMetadata(DecContainer.RecordMetadata value) {
    this.recordMetadata = value;
  }

  /**
   * Gets the value of the access property.
   * 
   * @return possible object is {@link DecContainer.Access }
   * 
   */
  public DecContainer.Access getAccess() {
    return access;
  }

  /**
   * Sets the value of the access property.
   * 
   * @param value allowed object is {@link DecContainer.Access }
   * 
   */
  public void setAccess(DecContainer.Access value) {
    this.access = value;
  }

  /**
   * Gets the value of the signatureMetadata property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the signatureMetadata property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getSignatureMetadata().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link DecContainer.SignatureMetadata }
   * 
   * @return list of {@link SignatureMetadata}
   */
  public List<DecContainer.SignatureMetadata> getSignatureMetadata() {
    if (signatureMetadata == null) {
      signatureMetadata = new ArrayList<DecContainer.SignatureMetadata>();
    }
    return this.signatureMetadata;
  }

  /**
   * Gets the value of the file property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the file property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getFile().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link DecContainer.File }
   * 
   * @return list of {@link File}
   */
  public List<DecContainer.File> getFile() {
    if (file == null) {
      file = new ArrayList<DecContainer.File>();
    }
    return this.file;
  }

  /**
   * Gets the value of the recordTypeSpecificMetadata property.
   * 
   * @return possible object is {@link DecContainer.RecordTypeSpecificMetadata }
   * 
   */
  public DecContainer.RecordTypeSpecificMetadata getRecordTypeSpecificMetadata() {
    return recordTypeSpecificMetadata;
  }

  /**
   * Sets the value of the recordTypeSpecificMetadata property.
   * 
   * @param value allowed object is {@link DecContainer.RecordTypeSpecificMetadata }
   * 
   */
  public void setRecordTypeSpecificMetadata(DecContainer.RecordTypeSpecificMetadata value) {
    this.recordTypeSpecificMetadata = value;
  }

  /**
   * Gets the value of the decMetadata property.
   * 
   * @return possible object is {@link DecContainer.DecMetadata }
   * 
   */
  public DecContainer.DecMetadata getDecMetadata() {
    return decMetadata;
  }

  /**
   * Sets the value of the decMetadata property.
   * 
   * @param value allowed object is {@link DecContainer.DecMetadata }
   * 
   */
  public void setDecMetadata(DecContainer.DecMetadata value) {
    this.decMetadata = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AccessConditionsCode" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}AccessConditionType"/&gt;
     *         &lt;element name="AccessRestriction" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="RestrictionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="RestrictionBeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="RestrictionEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="RestrictionEndEvent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="RestrictionInvalidSince" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="RestrictionBasis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="InformationOwner" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "accessConditionsCode",
      "accessRestriction"
  })
  public static class Access {

    @XmlElement(name = "AccessConditionsCode", required = true)
    @XmlSchemaType(name = "string")
    protected AccessConditionType accessConditionsCode;
    @XmlElement(name = "AccessRestriction")
    protected List<DecContainer.Access.AccessRestriction> accessRestriction;

    /**
     * Gets the value of the accessConditionsCode property.
     * 
     * @return possible object is {@link AccessConditionType }
     * 
     */
    public AccessConditionType getAccessConditionsCode() {
      return accessConditionsCode;
    }

    /**
     * Sets the value of the accessConditionsCode property.
     * 
     * @param value allowed object is {@link AccessConditionType }
     * 
     */
    public void setAccessConditionsCode(AccessConditionType value) {
      this.accessConditionsCode = value;
    }

    /**
     * Gets the value of the accessRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the accessRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
         *    getAccessRestriction().add(newItem);
         * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DecContainer.Access.AccessRestriction }
     * 
     * @return list of {@link AccessRestriction}
     */
    public List<DecContainer.Access.AccessRestriction> getAccessRestriction() {
      if (accessRestriction == null) {
        accessRestriction = new ArrayList<DecContainer.Access.AccessRestriction>();
      }
      return this.accessRestriction;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="RestrictionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="RestrictionBeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="RestrictionEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="RestrictionEndEvent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="RestrictionInvalidSince" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
         *         &lt;element name="RestrictionBasis" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="InformationOwner" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "restrictionIdentifier",
        "restrictionBeginDate",
        "restrictionEndDate",
        "restrictionEndEvent",
        "restrictionInvalidSince",
        "restrictionBasis",
        "informationOwner"
    })
    public static class AccessRestriction {

      @XmlElement(name = "RestrictionIdentifier")
      protected String restrictionIdentifier;
      @XmlElement(name = "RestrictionBeginDate", required = true)
      @XmlSchemaType(name = "date")
      protected XMLGregorianCalendar restrictionBeginDate;
      @XmlElement(name = "RestrictionEndDate", required = true)
      @XmlSchemaType(name = "date")
      protected XMLGregorianCalendar restrictionEndDate;
      @XmlElement(name = "RestrictionEndEvent")
      protected String restrictionEndEvent;
      @XmlElement(name = "RestrictionInvalidSince")
      @XmlSchemaType(name = "date")
      protected XMLGregorianCalendar restrictionInvalidSince;
      @XmlElement(name = "RestrictionBasis", required = true)
      protected String restrictionBasis;
      @XmlElement(name = "InformationOwner", required = true)
      protected String informationOwner;

      /**
       * Gets the value of the restrictionIdentifier property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getRestrictionIdentifier() {
        return restrictionIdentifier;
      }

      /**
       * Sets the value of the restrictionIdentifier property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setRestrictionIdentifier(String value) {
        this.restrictionIdentifier = value;
      }

      /**
       * Gets the value of the restrictionBeginDate property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getRestrictionBeginDate() {
        return restrictionBeginDate;
      }

      /**
       * Sets the value of the restrictionBeginDate property.
       * 
       * @param value allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setRestrictionBeginDate(XMLGregorianCalendar value) {
        this.restrictionBeginDate = value;
      }

      /**
       * Gets the value of the restrictionEndDate property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getRestrictionEndDate() {
        return restrictionEndDate;
      }

      /**
       * Sets the value of the restrictionEndDate property.
       * 
       * @param value allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setRestrictionEndDate(XMLGregorianCalendar value) {
        this.restrictionEndDate = value;
      }

      /**
       * Gets the value of the restrictionEndEvent property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getRestrictionEndEvent() {
        return restrictionEndEvent;
      }

      /**
       * Sets the value of the restrictionEndEvent property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setRestrictionEndEvent(String value) {
        this.restrictionEndEvent = value;
      }

      /**
       * Gets the value of the restrictionInvalidSince property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getRestrictionInvalidSince() {
        return restrictionInvalidSince;
      }

      /**
       * Sets the value of the restrictionInvalidSince property.
       * 
       * @param value allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setRestrictionInvalidSince(XMLGregorianCalendar value) {
        this.restrictionInvalidSince = value;
      }

      /**
       * Gets the value of the restrictionBasis property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getRestrictionBasis() {
        return restrictionBasis;
      }

      /**
       * Sets the value of the restrictionBasis property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setRestrictionBasis(String value) {
        this.restrictionBasis = value;
      }

      /**
       * Gets the value of the informationOwner property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getInformationOwner() {
        return informationOwner;
      }

      /**
       * Sets the value of the informationOwner property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setInformationOwner(String value) {
        this.informationOwner = value;
      }

    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DecId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="DecFolder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DecReceiptDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "decId",
      "decFolder",
      "decReceiptDate"
  })
  public static class DecMetadata {

    @XmlElement(name = "DecId", required = true)
    protected BigInteger decId;
    @XmlElement(name = "DecFolder", required = true)
    protected String decFolder;
    @XmlElement(name = "DecReceiptDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar decReceiptDate;

    /**
     * Gets the value of the decId property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getDecId() {
      return decId;
    }

    /**
     * Sets the value of the decId property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setDecId(BigInteger value) {
      this.decId = value;
    }

    /**
     * Gets the value of the decFolder property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDecFolder() {
      return decFolder;
    }

    /**
     * Sets the value of the decFolder property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDecFolder(String value) {
      this.decFolder = value;
    }

    /**
     * Gets the value of the decReceiptDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDecReceiptDate() {
      return decReceiptDate;
    }

    /**
     * Sets the value of the decReceiptDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setDecReceiptDate(XMLGregorianCalendar value) {
      this.decReceiptDate = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="FileGuid" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}GuidType"/&gt;
     *         &lt;element name="RecordMainComponent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MimeType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FileSize" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     *         &lt;element name="ZipBase64Content" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "fileGuid",
      "recordMainComponent",
      "fileName",
      "mimeType",
      "fileSize",
      "zipBase64Content"
  })
  public static class File {

    @XmlElement(name = "FileGuid", required = true)
    protected String fileGuid;
    @XmlElement(name = "RecordMainComponent")
    protected Boolean recordMainComponent;
    @XmlElement(name = "FileName", required = true)
    protected String fileName;
    @XmlElement(name = "MimeType", required = true)
    protected String mimeType;
    @XmlElement(name = "FileSize")
    protected BigInteger fileSize;
    @BigDataXmlElement(name = "ZipBase64Content")
    protected java.io.File zipBase64Content;

    /**
     * Gets the value of the fileGuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFileGuid() {
      return fileGuid;
    }

    /**
     * Sets the value of the fileGuid property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFileGuid(String value) {
      this.fileGuid = value;
    }

    /**
     * Gets the value of the recordMainComponent property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isRecordMainComponent() {
      return recordMainComponent;
    }

    /**
     * Sets the value of the recordMainComponent property.
     * 
     * @param value allowed object is {@link Boolean }
     * 
     */
    public void setRecordMainComponent(Boolean value) {
      this.recordMainComponent = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFileName() {
      return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFileName(String value) {
      this.fileName = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMimeType() {
      return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMimeType(String value) {
      this.mimeType = value;
    }

    /**
     * Gets the value of the fileSize property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getFileSize() {
      return fileSize;
    }

    /**
     * Sets the value of the fileSize property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setFileSize(BigInteger value) {
      this.fileSize = value;
    }

    /**
     * Gets the value of the zipBase64Content property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public java.io.File getZipBase64Content() {
      return zipBase64Content;
    }

    /**
     * Sets the value of the zipBase64Content property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setZipBase64Content(java.io.File value) {
      this.zipBase64Content = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="InitiatorRecordOriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="InitiatorRecordDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
     *         &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
     *         &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "initiatorRecordOriginalIdentifier",
      "initiatorRecordDate",
      "organisation",
      "person",
      "contactData"
  })
  public static class Initiator {

    @XmlElement(name = "InitiatorRecordOriginalIdentifier")
    protected String initiatorRecordOriginalIdentifier;
    @XmlElement(name = "InitiatorRecordDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar initiatorRecordDate;
    @XmlElement(name = "Organisation")
    protected OrganisationType organisation;
    @XmlElement(name = "Person")
    protected PersonType person;
    @XmlElement(name = "ContactData", required = true)
    protected ContactDataType contactData;

    /**
     * Gets the value of the initiatorRecordOriginalIdentifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInitiatorRecordOriginalIdentifier() {
      return initiatorRecordOriginalIdentifier;
    }

    /**
     * Sets the value of the initiatorRecordOriginalIdentifier property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInitiatorRecordOriginalIdentifier(String value) {
      this.initiatorRecordOriginalIdentifier = value;
    }

    /**
     * Gets the value of the initiatorRecordDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getInitiatorRecordDate() {
      return initiatorRecordDate;
    }

    /**
     * Sets the value of the initiatorRecordDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setInitiatorRecordDate(XMLGregorianCalendar value) {
      this.initiatorRecordDate = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return possible object is {@link OrganisationType }
     * 
     */
    public OrganisationType getOrganisation() {
      return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value allowed object is {@link OrganisationType }
     * 
     */
    public void setOrganisation(OrganisationType value) {
      this.organisation = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return possible object is {@link PersonType }
     * 
     */
    public PersonType getPerson() {
      return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value allowed object is {@link PersonType }
     * 
     */
    public void setPerson(PersonType value) {
      this.person = value;
    }

    /**
     * Gets the value of the contactData property.
     * 
     * @return possible object is {@link ContactDataType }
     * 
     */
    public ContactDataType getContactData() {
      return contactData;
    }

    /**
     * Sets the value of the contactData property.
     * 
     * @param value allowed object is {@link ContactDataType }
     * 
     */
    public void setContactData(ContactDataType value) {
      this.contactData = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RecipientRecordGuid" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}GuidType" minOccurs="0"/&gt;
     *         &lt;element name="RecipientRecordOriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="MessageForRecipient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
     *         &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
     *         &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "recipientRecordGuid",
      "recipientRecordOriginalIdentifier",
      "messageForRecipient",
      "organisation",
      "person",
      "contactData"
  })
  public static class Recipient {

    @XmlElement(name = "RecipientRecordGuid")
    protected String recipientRecordGuid;
    @XmlElement(name = "RecipientRecordOriginalIdentifier")
    protected String recipientRecordOriginalIdentifier;
    @XmlElement(name = "MessageForRecipient")
    protected String messageForRecipient;
    @XmlElement(name = "Organisation")
    protected OrganisationType organisation;
    @XmlElement(name = "Person")
    protected PersonType person;
    @XmlElement(name = "ContactData")
    protected ContactDataType contactData;

    /**
     * Gets the value of the recipientRecordGuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecipientRecordGuid() {
      return recipientRecordGuid;
    }

    /**
     * Sets the value of the recipientRecordGuid property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecipientRecordGuid(String value) {
      this.recipientRecordGuid = value;
    }

    /**
     * Gets the value of the recipientRecordOriginalIdentifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecipientRecordOriginalIdentifier() {
      return recipientRecordOriginalIdentifier;
    }

    /**
     * Sets the value of the recipientRecordOriginalIdentifier property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecipientRecordOriginalIdentifier(String value) {
      this.recipientRecordOriginalIdentifier = value;
    }

    /**
     * Gets the value of the messageForRecipient property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMessageForRecipient() {
      return messageForRecipient;
    }

    /**
     * Sets the value of the messageForRecipient property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMessageForRecipient(String value) {
      this.messageForRecipient = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return possible object is {@link OrganisationType }
     * 
     */
    public OrganisationType getOrganisation() {
      return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value allowed object is {@link OrganisationType }
     * 
     */
    public void setOrganisation(OrganisationType value) {
      this.organisation = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return possible object is {@link PersonType }
     * 
     */
    public PersonType getPerson() {
      return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value allowed object is {@link PersonType }
     * 
     */
    public void setPerson(PersonType value) {
      this.person = value;
    }

    /**
     * Gets the value of the contactData property.
     * 
     * @return possible object is {@link ContactDataType }
     * 
     */
    public ContactDataType getContactData() {
      return contactData;
    }

    /**
     * Sets the value of the contactData property.
     * 
     * @param value allowed object is {@link ContactDataType }
     * 
     */
    public void setContactData(ContactDataType value) {
      this.contactData = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
     *         &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
     *         &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "organisation",
      "person",
      "contactData"
  })
  public static class RecordCreator {

    @XmlElement(name = "Organisation")
    protected OrganisationType organisation;
    @XmlElement(name = "Person")
    protected PersonType person;
    @XmlElement(name = "ContactData")
    protected ContactDataType contactData;

    /**
     * Gets the value of the organisation property.
     * 
     * @return possible object is {@link OrganisationType }
     * 
     */
    public OrganisationType getOrganisation() {
      return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value allowed object is {@link OrganisationType }
     * 
     */
    public void setOrganisation(OrganisationType value) {
      this.organisation = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return possible object is {@link PersonType }
     * 
     */
    public PersonType getPerson() {
      return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value allowed object is {@link PersonType }
     * 
     */
    public void setPerson(PersonType value) {
      this.person = value;
    }

    /**
     * Gets the value of the contactData property.
     * 
     * @return possible object is {@link ContactDataType }
     * 
     */
    public ContactDataType getContactData() {
      return contactData;
    }

    /**
     * Sets the value of the contactData property.
     * 
     * @param value allowed object is {@link ContactDataType }
     * 
     */
    public void setContactData(ContactDataType value) {
      this.contactData = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RecordGuid" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}GuidType"/&gt;
     *         &lt;element name="RecordType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RecordOriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RecordDateRegistered" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="RecordTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RecordLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RecordAbstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ReplyDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "recordGuid",
      "recordType",
      "recordOriginalIdentifier",
      "recordDateRegistered",
      "recordTitle",
      "recordLanguage",
      "recordAbstract",
      "replyDueDate"
  })
  public static class RecordMetadata {

    @XmlElement(name = "RecordGuid", required = true)
    protected String recordGuid;
    @XmlElement(name = "RecordType", required = true)
    protected String recordType;
    @XmlElement(name = "RecordOriginalIdentifier", required = true)
    protected String recordOriginalIdentifier;
    @XmlElement(name = "RecordDateRegistered", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar recordDateRegistered;
    @XmlElement(name = "RecordTitle", required = true)
    protected String recordTitle;
    @XmlElement(name = "RecordLanguage")
    protected String recordLanguage;
    @XmlElement(name = "RecordAbstract")
    protected String recordAbstract;
    @XmlElement(name = "ReplyDueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar replyDueDate;

    /**
     * Gets the value of the recordGuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordGuid() {
      return recordGuid;
    }

    /**
     * Sets the value of the recordGuid property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordGuid(String value) {
      this.recordGuid = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordType() {
      return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordType(String value) {
      this.recordType = value;
    }

    /**
     * Gets the value of the recordOriginalIdentifier property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordOriginalIdentifier() {
      return recordOriginalIdentifier;
    }

    /**
     * Sets the value of the recordOriginalIdentifier property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordOriginalIdentifier(String value) {
      this.recordOriginalIdentifier = value;
    }

    /**
     * Gets the value of the recordDateRegistered property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getRecordDateRegistered() {
      return recordDateRegistered;
    }

    /**
     * Sets the value of the recordDateRegistered property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setRecordDateRegistered(XMLGregorianCalendar value) {
      this.recordDateRegistered = value;
    }

    /**
     * Gets the value of the recordTitle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordTitle() {
      return recordTitle;
    }

    /**
     * Sets the value of the recordTitle property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordTitle(String value) {
      this.recordTitle = value;
    }

    /**
     * Gets the value of the recordLanguage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordLanguage() {
      return recordLanguage;
    }

    /**
     * Sets the value of the recordLanguage property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordLanguage(String value) {
      this.recordLanguage = value;
    }

    /**
     * Gets the value of the recordAbstract property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRecordAbstract() {
      return recordAbstract;
    }

    /**
     * Sets the value of the recordAbstract property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setRecordAbstract(String value) {
      this.recordAbstract = value;
    }

    /**
     * Gets the value of the replyDueDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getReplyDueDate() {
      return replyDueDate;
    }

    /**
     * Sets the value of the replyDueDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setReplyDueDate(XMLGregorianCalendar value) {
      this.replyDueDate = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Organisation" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}OrganisationType" minOccurs="0"/&gt;
     *         &lt;element name="Person" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}PersonType" minOccurs="0"/&gt;
     *         &lt;element name="ContactData" type="{http://www.riik.ee/schemas/deccontainer/vers_2_1/}ContactDataType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "organisation",
      "person",
      "contactData"
  })
  public static class RecordSenderToDec {

    @XmlElement(name = "Organisation")
    protected OrganisationType organisation;
    @XmlElement(name = "Person")
    protected PersonType person;
    @XmlElement(name = "ContactData")
    protected ContactDataType contactData;

    /**
     * Gets the value of the organisation property.
     * 
     * @return possible object is {@link OrganisationType }
     * 
     */
    public OrganisationType getOrganisation() {
      return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value allowed object is {@link OrganisationType }
     * 
     */
    public void setOrganisation(OrganisationType value) {
      this.organisation = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return possible object is {@link PersonType }
     * 
     */
    public PersonType getPerson() {
      return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value allowed object is {@link PersonType }
     * 
     */
    public void setPerson(PersonType value) {
      this.person = value;
    }

    /**
     * Gets the value of the contactData property.
     * 
     * @return possible object is {@link ContactDataType }
     * 
     */
    public ContactDataType getContactData() {
      return contactData;
    }

    /**
     * Sets the value of the contactData property.
     * 
     * @param value allowed object is {@link ContactDataType }
     * 
     */
    public void setContactData(ContactDataType value) {
      this.contactData = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "any"
  })
  public static class RecordTypeSpecificMetadata {

    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
         *    getAny().add(newItem);
         * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Element }
     * 
     * @return list of {@link Element}
     */
    public List<Element> getAny() {
      if (any == null) {
        any = new ArrayList<Element>();
      }
      return this.any;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SignatureType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Signer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Verified" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SignatureVerificationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "signatureType",
      "signer",
      "verified",
      "signatureVerificationDate"
  })
  public static class SignatureMetadata {

    @XmlElement(name = "SignatureType")
    protected String signatureType;
    @XmlElement(name = "Signer")
    protected String signer;
    @XmlElement(name = "Verified")
    protected String verified;
    @XmlElement(name = "SignatureVerificationDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar signatureVerificationDate;

    /**
     * Gets the value of the signatureType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSignatureType() {
      return signatureType;
    }

    /**
     * Sets the value of the signatureType property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSignatureType(String value) {
      this.signatureType = value;
    }

    /**
     * Gets the value of the signer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSigner() {
      return signer;
    }

    /**
     * Sets the value of the signer property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSigner(String value) {
      this.signer = value;
    }

    /**
     * Gets the value of the verified property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVerified() {
      return verified;
    }

    /**
     * Sets the value of the verified property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setVerified(String value) {
      this.verified = value;
    }

    /**
     * Gets the value of the signatureVerificationDate property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getSignatureVerificationDate() {
      return signatureVerificationDate;
    }

    /**
     * Sets the value of the signatureVerificationDate property.
     * 
     * @param value allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setSignatureVerificationDate(XMLGregorianCalendar value) {
      this.signatureVerificationDate = value;
    }

  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DecSender"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PersonalIdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DecRecipient" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="PersonalIdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "decSender",
      "decRecipient"
  })
  public static class Transport {

    @XmlElement(name = "DecSender", required = true)
    protected DecContainer.Transport.DecSender decSender;
    @XmlElement(name = "DecRecipient", required = true)
    protected List<DecContainer.Transport.DecRecipient> decRecipient;

    /**
     * Gets the value of the decSender property.
     * 
     * @return possible object is {@link DecContainer.Transport.DecSender }
     * 
     */
    public DecContainer.Transport.DecSender getDecSender() {
      return decSender;
    }

    /**
     * Sets the value of the decSender property.
     * 
     * @param value allowed object is {@link DecContainer.Transport.DecSender }
     * 
     */
    public void setDecSender(DecContainer.Transport.DecSender value) {
      this.decSender = value;
    }

    /**
     * Gets the value of the decRecipient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the decRecipient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
         *    getDecRecipient().add(newItem);
         * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DecContainer.Transport.DecRecipient }
     * 
     * @return list of {@link DecRecipient}
     */
    public List<DecContainer.Transport.DecRecipient> getDecRecipient() {
      if (decRecipient == null) {
        decRecipient = new ArrayList<DecContainer.Transport.DecRecipient>();
      }
      return this.decRecipient;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PersonalIdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organisationCode",
        "structuralUnit",
        "personalIdCode"
    })
    public static class DecRecipient {

      @XmlElement(name = "OrganisationCode", required = true)
      protected String organisationCode;
      @XmlElement(name = "StructuralUnit")
      protected String structuralUnit;
      @XmlElement(name = "PersonalIdCode")
      protected String personalIdCode;

      /**
       * Gets the value of the organisationCode property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getOrganisationCode() {
        return organisationCode;
      }

      /**
       * Sets the value of the organisationCode property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setOrganisationCode(String value) {
        this.organisationCode = value;
      }

      /**
       * Gets the value of the structuralUnit property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getStructuralUnit() {
        return structuralUnit;
      }

      /**
       * Sets the value of the structuralUnit property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setStructuralUnit(String value) {
        this.structuralUnit = value;
      }

      /**
       * Gets the value of the personalIdCode property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getPersonalIdCode() {
        return personalIdCode;
      }

      /**
       * Sets the value of the personalIdCode property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setPersonalIdCode(String value) {
        this.personalIdCode = value;
      }

    }


    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="PersonalIdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organisationCode",
        "structuralUnit",
        "personalIdCode"
    })
    public static class DecSender {

      @XmlElement(name = "OrganisationCode", required = true)
      protected String organisationCode;
      @XmlElement(name = "StructuralUnit")
      protected String structuralUnit;
      @XmlElement(name = "PersonalIdCode")
      protected String personalIdCode;

      /**
       * Gets the value of the organisationCode property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getOrganisationCode() {
        return organisationCode;
      }

      /**
       * Sets the value of the organisationCode property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setOrganisationCode(String value) {
        this.organisationCode = value;
      }

      /**
       * Gets the value of the structuralUnit property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getStructuralUnit() {
        return structuralUnit;
      }

      /**
       * Sets the value of the structuralUnit property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setStructuralUnit(String value) {
        this.structuralUnit = value;
      }

      /**
       * Gets the value of the personalIdCode property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getPersonalIdCode() {
        return personalIdCode;
      }

      /**
       * Sets the value of the personalIdCode property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setPersonalIdCode(String value) {
        this.personalIdCode = value;
      }

    }

  }

}
