//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.ee.riik.schemas.deccontainer.vers_2_1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the ee.riik.schemas.deccontainer.vers_2_1 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: ee.riik.schemas.deccontainer.vers_2_1
   * 
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link DecContainer }
   * 
   * @return created object
   */
  public DecContainer createDecContainer() {
    return new DecContainer();
  }

  /**
   * Create an instance of {@link DecContainer.Access }
   * 
   * @return created object
   */
  public DecContainer.Access createDecContainerAccess() {
    return new DecContainer.Access();
  }

  /**
   * Create an instance of {@link DecContainer.Transport }
   * 
   * @return created object
   */
  public DecContainer.Transport createDecContainerTransport() {
    return new DecContainer.Transport();
  }

  /**
   * Create an instance of {@link DecContainer.Initiator }
   * 
   * @return created object
   */
  public DecContainer.Initiator createDecContainerInitiator() {
    return new DecContainer.Initiator();
  }

  /**
   * Create an instance of {@link DecContainer.RecordCreator }
   * 
   * @return created object
   */
  public DecContainer.RecordCreator createDecContainerRecordCreator() {
    return new DecContainer.RecordCreator();
  }

  /**
   * Create an instance of {@link DecContainer.RecordSenderToDec }
   * 
   * @return created object
   */
  public DecContainer.RecordSenderToDec createDecContainerRecordSenderToDec() {
    return new DecContainer.RecordSenderToDec();
  }

  /**
   * Create an instance of {@link DecContainer.Recipient }
   * 
   * @return created object
   */
  public DecContainer.Recipient createDecContainerRecipient() {
    return new DecContainer.Recipient();
  }

  /**
   * Create an instance of {@link DecContainer.RecordMetadata }
   * 
   * @return created object
   */
  public DecContainer.RecordMetadata createDecContainerRecordMetadata() {
    return new DecContainer.RecordMetadata();
  }

  /**
   * Create an instance of {@link DecContainer.SignatureMetadata }
   * 
   * @return created object
   */
  public DecContainer.SignatureMetadata createDecContainerSignatureMetadata() {
    return new DecContainer.SignatureMetadata();
  }

  /**
   * Create an instance of {@link DecContainer.File }
   * 
   * @return created object
   */
  public DecContainer.File createDecContainerFile() {
    return new DecContainer.File();
  }

  /**
   * Create an instance of {@link DecContainer.RecordTypeSpecificMetadata }
   * 
   * @return created object
   */
  public DecContainer.RecordTypeSpecificMetadata createDecContainerRecordTypeSpecificMetadata() {
    return new DecContainer.RecordTypeSpecificMetadata();
  }

  /**
   * Create an instance of {@link DecContainer.DecMetadata }
   * 
   * @return created object
   */
  public DecContainer.DecMetadata createDecContainerDecMetadata() {
    return new DecContainer.DecMetadata();
  }

  /**
   * Create an instance of {@link OrganisationType }
   * 
   * @return created object
   */
  public OrganisationType createOrganisationType() {
    return new OrganisationType();
  }

  /**
   * Create an instance of {@link PersonType }
   * 
   * @return created object
   */
  public PersonType createPersonType() {
    return new PersonType();
  }

  /**
   * Create an instance of {@link ContactDataType }
   * 
   * @return created object
   */
  public ContactDataType createContactDataType() {
    return new ContactDataType();
  }

  /**
   * Create an instance of {@link PostalAddressType }
   * 
   * @return created object
   */
  public PostalAddressType createPostalAddressType() {
    return new PostalAddressType();
  }

  /**
   * Create an instance of {@link DecContainer.Access.AccessRestriction }
   * 
   * @return created object
   */
  public DecContainer.Access.AccessRestriction createDecContainerAccessAccessRestriction() {
    return new DecContainer.Access.AccessRestriction();
  }

  /**
   * Create an instance of {@link DecContainer.Transport.DecSender }
   * 
   * @return created object
   */
  public DecContainer.Transport.DecSender createDecContainerTransportDecSender() {
    return new DecContainer.Transport.DecSender();
  }

  /**
   * Create an instance of {@link DecContainer.Transport.DecRecipient }
   * 
   * @return created object
   */
  public DecContainer.Transport.DecRecipient createDecContainerTransportDecRecipient() {
    return new DecContainer.Transport.DecRecipient();
  }

}
