//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.ee.riik.schemas.deccontainer.vers_2_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for OrganisationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganisationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OrganisationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StructuralUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PositionTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Residency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganisationType", propOrder = {
    "name",
    "organisationCode",
    "structuralUnit",
    "positionTitle",
    "residency"
})
public class OrganisationType {

  @XmlElement(name = "Name", required = true)
  protected String name;
  @XmlElement(name = "OrganisationCode")
  protected String organisationCode;
  @XmlElement(name = "StructuralUnit")
  protected String structuralUnit;
  @XmlElement(name = "PositionTitle")
  protected String positionTitle;
  @XmlElement(name = "Residency")
  protected String residency;

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the organisationCode property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOrganisationCode() {
    return organisationCode;
  }

  /**
   * Sets the value of the organisationCode property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setOrganisationCode(String value) {
    this.organisationCode = value;
  }

  /**
   * Gets the value of the structuralUnit property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStructuralUnit() {
    return structuralUnit;
  }

  /**
   * Sets the value of the structuralUnit property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setStructuralUnit(String value) {
    this.structuralUnit = value;
  }

  /**
   * Gets the value of the positionTitle property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPositionTitle() {
    return positionTitle;
  }

  /**
   * Sets the value of the positionTitle property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setPositionTitle(String value) {
    this.positionTitle = value;
  }

  /**
   * Gets the value of the residency property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getResidency() {
    return residency;
  }

  /**
   * Sets the value of the residency property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setResidency(String value) {
    this.residency = value;
  }

}
