//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.eu.x_road.xsd.xroad;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for SecurityServerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityServerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}IDREF"/&gt;
 *         &lt;element name="serverCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="authCertHash" type="{http://www.w3.org/2001/XMLSchema}base64Binary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="client" type="{http://www.w3.org/2001/XMLSchema}IDREF" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityServerType", propOrder = {
    "owner",
    "serverCode",
    "address",
    "authCertHash",
    "client"
})
public class SecurityServerType {

  @XmlElement(required = true)
  @XmlIDREF
  @XmlSchemaType(name = "IDREF")
  protected Object owner;
  @XmlElement(required = true)
  protected String serverCode;
  protected String address;
  protected List<byte[]> authCertHash;
  @XmlElementRef(name = "client", type = JAXBElement.class, required = false)
  protected List<JAXBElement<Object>> client;

  /**
   * Gets the value of the owner property.
   * 
   * @return possible object is {@link Object }
   * 
   */
  public Object getOwner() {
    return owner;
  }

  /**
   * Sets the value of the owner property.
   * 
   * @param value allowed object is {@link Object }
   * 
   */
  public void setOwner(Object value) {
    this.owner = value;
  }

  /**
   * Gets the value of the serverCode property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getServerCode() {
    return serverCode;
  }

  /**
   * Sets the value of the serverCode property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setServerCode(String value) {
    this.serverCode = value;
  }

  /**
   * Gets the value of the address property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getAddress() {
    return address;
  }

  /**
   * Sets the value of the address property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setAddress(String value) {
    this.address = value;
  }

  /**
   * Gets the value of the authCertHash property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the authCertHash property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getAuthCertHash().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list byte[]
   * 
   * @return list of byte
   */
  public List<byte[]> getAuthCertHash() {
    if (authCertHash == null) {
      authCertHash = new ArrayList<byte[]>();
    }
    return this.authCertHash;
  }

  /**
   * Gets the value of the client property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the client property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getClient().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link JAXBElement }{@code <}
   * {@link Object }{@code >}
   * 
   * @return list of {@link JAXBElement}
   */
  public List<JAXBElement<Object>> getClient() {
    if (client == null) {
      client = new ArrayList<JAXBElement<Object>>();
    }
    return this.client;
  }

}
