//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.eu.x_road.xsd.xroad;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for SharedParametersType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SharedParametersType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="instanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="approvedCA" type="{http://x-road.eu/xsd/xroad.xsd}ApprovedCAType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="approvedTSA" type="{http://x-road.eu/xsd/xroad.xsd}ApprovedTSAType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="member" type="{http://x-road.eu/xsd/xroad.xsd}MemberType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="securityServer" type="{http://x-road.eu/xsd/xroad.xsd}SecurityServerType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="globalGroup" type="{http://x-road.eu/xsd/xroad.xsd}GlobalGroupType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="centralService" type="{http://x-road.eu/xsd/xroad.xsd}CentralServiceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="globalSettings" type="{http://x-road.eu/xsd/xroad.xsd}GlobalSettingsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SharedParametersType", propOrder = {
    "instanceIdentifier",
    "approvedCA",
    "approvedTSA",
    "member",
    "securityServer",
    "globalGroup",
    "centralService",
    "globalSettings"
})
public class SharedParametersType {

  @XmlElement(required = true)
  protected String instanceIdentifier;
  protected List<ApprovedCAType> approvedCA;
  protected List<ApprovedTSAType> approvedTSA;
  protected List<MemberType> member;
  protected List<SecurityServerType> securityServer;
  protected List<GlobalGroupType> globalGroup;
  protected List<CentralServiceType> centralService;
  @XmlElement(required = true)
  protected GlobalSettingsType globalSettings;

  /**
   * Gets the value of the instanceIdentifier property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getInstanceIdentifier() {
    return instanceIdentifier;
  }

  /**
   * Sets the value of the instanceIdentifier property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setInstanceIdentifier(String value) {
    this.instanceIdentifier = value;
  }

  /**
   * Gets the value of the approvedCA property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the approvedCA property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getApprovedCA().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ApprovedCAType }
   * 
   * 
   */
  public List<ApprovedCAType> getApprovedCA() {
    if (approvedCA == null) {
      approvedCA = new ArrayList<ApprovedCAType>();
    }
    return this.approvedCA;
  }

  /**
   * Gets the value of the approvedTSA property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the approvedTSA property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getApprovedTSA().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link ApprovedTSAType }
   * 
   * 
   */
  public List<ApprovedTSAType> getApprovedTSA() {
    if (approvedTSA == null) {
      approvedTSA = new ArrayList<ApprovedTSAType>();
    }
    return this.approvedTSA;
  }

  /**
   * Gets the value of the member property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the member property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getMember().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link MemberType }
   * 
   * 
   */
  public List<MemberType> getMember() {
    if (member == null) {
      member = new ArrayList<MemberType>();
    }
    return this.member;
  }

  /**
   * Gets the value of the securityServer property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the securityServer property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getSecurityServer().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link SecurityServerType }
   * 
   * 
   */
  public List<SecurityServerType> getSecurityServer() {
    if (securityServer == null) {
      securityServer = new ArrayList<SecurityServerType>();
    }
    return this.securityServer;
  }

  /**
   * Gets the value of the globalGroup property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the globalGroup property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getGlobalGroup().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link GlobalGroupType }
   * 
   * 
   */
  public List<GlobalGroupType> getGlobalGroup() {
    if (globalGroup == null) {
      globalGroup = new ArrayList<GlobalGroupType>();
    }
    return this.globalGroup;
  }

  /**
   * Gets the value of the centralService property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the centralService property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getCentralService().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link CentralServiceType }
   * 
   * 
   */
  public List<CentralServiceType> getCentralService() {
    if (centralService == null) {
      centralService = new ArrayList<CentralServiceType>();
    }
    return this.centralService;
  }

  /**
   * Gets the value of the globalSettings property.
   * 
   * @return possible object is {@link GlobalSettingsType }
   * 
   */
  public GlobalSettingsType getGlobalSettings() {
    return globalSettings;
  }

  /**
   * Sets the value of the globalSettings property.
   * 
   * @param value allowed object is {@link GlobalSettingsType }
   * 
   */
  public void setGlobalSettings(GlobalSettingsType value) {
    this.globalSettings = value;
  }

}
