//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 09:18:04 PM EET 
//


package ee.riik.xrd.dhl.producers.producer.dhl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getSendingOptionsV2RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getSendingOptionsV2RequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="asutused" type="{http://producers.dhl.xrd.riik.ee/producer/dhl}institutionRefsArrayType" minOccurs="0"/&gt;
 *         &lt;element name="vastuvotmata_dokumente_ootel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="vahetatud_dokumente_vahemalt" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="vahetatud_dokumente_kuni" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSendingOptionsV2RequestType", propOrder = {
    "asutused",
    "vastuvotmataDokumenteOotel",
    "vahetatudDokumenteVahemalt",
    "vahetatudDokumenteKuni"
})
public class GetSendingOptionsV2RequestType {

    protected InstitutionRefsArrayType asutused;
    @XmlElement(name = "vastuvotmata_dokumente_ootel")
    protected Boolean vastuvotmataDokumenteOotel;
    @XmlElement(name = "vahetatud_dokumente_vahemalt")
    protected BigInteger vahetatudDokumenteVahemalt;
    @XmlElement(name = "vahetatud_dokumente_kuni")
    protected BigInteger vahetatudDokumenteKuni;

    /**
     * Gets the value of the asutused property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionRefsArrayType }
     *     
     */
    public InstitutionRefsArrayType getAsutused() {
        return asutused;
    }

    /**
     * Sets the value of the asutused property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionRefsArrayType }
     *     
     */
    public void setAsutused(InstitutionRefsArrayType value) {
        this.asutused = value;
    }

    /**
     * Gets the value of the vastuvotmataDokumenteOotel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVastuvotmataDokumenteOotel() {
        return vastuvotmataDokumenteOotel;
    }

    /**
     * Sets the value of the vastuvotmataDokumenteOotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVastuvotmataDokumenteOotel(Boolean value) {
        this.vastuvotmataDokumenteOotel = value;
    }

    /**
     * Gets the value of the vahetatudDokumenteVahemalt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVahetatudDokumenteVahemalt() {
        return vahetatudDokumenteVahemalt;
    }

    /**
     * Sets the value of the vahetatudDokumenteVahemalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVahetatudDokumenteVahemalt(BigInteger value) {
        this.vahetatudDokumenteVahemalt = value;
    }

    /**
     * Gets the value of the vahetatudDokumenteKuni property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVahetatudDokumenteKuni() {
        return vahetatudDokumenteKuni;
    }

    /**
     * Sets the value of the vahetatudDokumenteKuni property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVahetatudDokumenteKuni(BigInteger value) {
        this.vahetatudDokumenteKuni = value;
    }

}
