//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package eu.x_road.xsd.representation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the eu.x_road.xsd.representation package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _PartyClass_QNAME = new QName(
      "http://x-road.eu/xsd/representation.xsd", "partyClass");
  private final static QName _PartyCode_QNAME = new QName(
      "http://x-road.eu/xsd/representation.xsd", "partyCode");
  private final static QName _RepresentedParty_QNAME = new QName(
      "http://x-road.eu/xsd/representation.xsd", "representedParty");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: eu.x_road.xsd.representation
   * 
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link XRoadRepresentedPartyType }
   * 
   */
  public XRoadRepresentedPartyType createXRoadRepresentedPartyType() {
    return new XRoadRepresentedPartyType();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/representation.xsd", name = "partyClass")
  public JAXBElement<String> createPartyClass(String value) {
    return new JAXBElement<String>(_PartyClass_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/representation.xsd", name = "partyCode")
  public JAXBElement<String> createPartyCode(String value) {
    return new JAXBElement<String>(_PartyCode_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link XRoadRepresentedPartyType }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/representation.xsd", name = "representedParty")
  public JAXBElement<XRoadRepresentedPartyType> createRepresentedParty(
      XRoadRepresentedPartyType value) {
    return new JAXBElement<XRoadRepresentedPartyType>(_RepresentedParty_QNAME,
        XRoadRepresentedPartyType.class, null, value);
  }

}
