//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package eu.x_road.dhx.producer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for fault complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fault"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="faultCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="faultString" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fault", propOrder = {
    "faultCode",
    "faultString"
})
public class Fault {

  @XmlElement(required = true)
  protected String faultCode;
  @XmlElement(required = true)
  protected String faultString;

  /**
   * Gets the value of the faultCode property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFaultCode() {
    return faultCode;
  }

  /**
   * Sets the value of the faultCode property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFaultCode(String value) {
    this.faultCode = value;
  }

  /**
   * Gets the value of the faultString property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFaultString() {
    return faultString;
  }

  /**
   * Sets the value of the faultString property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFaultString(String value) {
    this.faultString = value;
  }

}
