//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>
 * Java class for AccessRightsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessRightsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Restriction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessRightsType", propOrder = {
    "restriction",
    "beginDate",
    "endDate",
    "reason"
})
public class AccessRightsType {

  @XmlElement(name = "Restriction", required = true)
  protected String restriction;
  @XmlElement(name = "BeginDate", required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar beginDate;
  @XmlElement(name = "EndDate", required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar endDate;
  @XmlElement(name = "Reason", required = true)
  protected String reason;

  /**
   * Gets the value of the restriction property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRestriction() {
    return restriction;
  }

  /**
   * Sets the value of the restriction property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRestriction(String value) {
    this.restriction = value;
  }

  /**
   * Gets the value of the beginDate property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getBeginDate() {
    return beginDate;
  }

  /**
   * Sets the value of the beginDate property.
   * 
   * @param value allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setBeginDate(XMLGregorianCalendar value) {
    this.beginDate = value;
  }

  /**
   * Gets the value of the endDate property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getEndDate() {
    return endDate;
  }

  /**
   * Sets the value of the endDate property.
   * 
   * @param value allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setEndDate(XMLGregorianCalendar value) {
    this.endDate = value;
  }

  /**
   * Gets the value of the reason property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReason() {
    return reason;
  }

  /**
   * Sets the value of the reason property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setReason(String value) {
    this.reason = value;
  }

}
