//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for Letter complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Letter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Addressees" type="{http://www.riik.ee/schemas/dhl/rkel_letter}Addressee"/&gt;
 *         &lt;element name="Author" type="{http://www.riik.ee/schemas/dhl/rkel_letter}PartyType"/&gt;
 *         &lt;element name="Signatures" type="{http://www.riik.ee/schemas/dhl/rkel_letter}Signature"/&gt;
 *         &lt;element name="Compilators" type="{http://www.riik.ee/schemas/dhl/rkel_letter}Compilator"/&gt;
 *         &lt;element name="LetterMetaData" type="{http://www.riik.ee/schemas/dhl/rkel_letter}LetterType"/&gt;
 *         &lt;element name="signeddoc" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Letter", propOrder = {
    "addressees",
    "author",
    "signatures",
    "compilators",
    "letterMetaData",
    "signeddoc"
})
public class Letter {

  @XmlElement(name = "Addressees", required = true)
  protected Addressee addressees;
  @XmlElement(name = "Author", required = true)
  protected PartyType author;
  @XmlElement(name = "Signatures", required = true)
  protected Signature signatures;
  @XmlElement(name = "Compilators", required = true)
  protected Compilator compilators;
  @XmlElement(name = "LetterMetaData", required = true)
  protected LetterType letterMetaData;
  @XmlElement(required = true)
  protected byte[] signeddoc;

  /**
   * Gets the value of the addressees property.
   * 
   * @return possible object is {@link Addressee }
   * 
   */
  public Addressee getAddressees() {
    return addressees;
  }

  /**
   * Sets the value of the addressees property.
   * 
   * @param value allowed object is {@link Addressee }
   * 
   */
  public void setAddressees(Addressee value) {
    this.addressees = value;
  }

  /**
   * Gets the value of the author property.
   * 
   * @return possible object is {@link PartyType }
   * 
   */
  public PartyType getAuthor() {
    return author;
  }

  /**
   * Sets the value of the author property.
   * 
   * @param value allowed object is {@link PartyType }
   * 
   */
  public void setAuthor(PartyType value) {
    this.author = value;
  }

  /**
   * Gets the value of the signatures property.
   * 
   * @return possible object is {@link Signature }
   * 
   */
  public Signature getSignatures() {
    return signatures;
  }

  /**
   * Sets the value of the signatures property.
   * 
   * @param value allowed object is {@link Signature }
   * 
   */
  public void setSignatures(Signature value) {
    this.signatures = value;
  }

  /**
   * Gets the value of the compilators property.
   * 
   * @return possible object is {@link Compilator }
   * 
   */
  public Compilator getCompilators() {
    return compilators;
  }

  /**
   * Sets the value of the compilators property.
   * 
   * @param value allowed object is {@link Compilator }
   * 
   */
  public void setCompilators(Compilator value) {
    this.compilators = value;
  }

  /**
   * Gets the value of the letterMetaData property.
   * 
   * @return possible object is {@link LetterType }
   * 
   */
  public LetterType getLetterMetaData() {
    return letterMetaData;
  }

  /**
   * Sets the value of the letterMetaData property.
   * 
   * @param value allowed object is {@link LetterType }
   * 
   */
  public void setLetterMetaData(LetterType value) {
    this.letterMetaData = value;
  }

  /**
   * Gets the value of the signeddoc property.
   * 
   * @return possible object is byte[]
   */
  public byte[] getSigneddoc() {
    return signeddoc;
  }

  /**
   * Sets the value of the signeddoc property.
   * 
   * @param value allowed object is byte[]
   */
  public void setSigneddoc(byte[] value) {
    this.signeddoc = value;
  }

}
