//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>
 * Java class for LetterType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LetterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SignDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="SenderIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OriginalIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Languange" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Deadline" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Enclosures" type="{http://www.riik.ee/schemas/dhl/rkel_letter}Enclosure" minOccurs="0"/&gt;
 *         &lt;element name="AccessRights" type="{http://www.riik.ee/schemas/dhl/rkel_letter}AccessRightsType" minOccurs="0"/&gt;
 *         &lt;element name="IntellectualPropertyRights" type="{http://www.riik.ee/schemas/dhl/rkel_letter}IntellectualPropertyRightsType" minOccurs="0"/&gt;
 *         &lt;element name="NoCopies" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderSeriesTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderFolderTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderVitalRecordIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LetterType", propOrder = {
    "signDate",
    "senderIdentifier",
    "originalIdentifier",
    "type",
    "languange",
    "version",
    "title",
    "deadline",
    "enclosures",
    "accessRights",
    "intellectualPropertyRights",
    "noCopies",
    "senderSeriesTitle",
    "senderFolderTitle",
    "senderVitalRecordIndicator"
})
public class LetterType {

  @XmlElement(name = "SignDate", required = true)
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar signDate;
  @XmlElement(name = "SenderIdentifier", required = true)
  protected String senderIdentifier;
  @XmlElement(name = "OriginalIdentifier")
  protected String originalIdentifier;
  @XmlElement(name = "Type", required = true)
  protected String type;
  @XmlElement(name = "Languange", required = true)
  protected String languange;
  @XmlElement(name = "Version")
  protected String version;
  @XmlElement(name = "Title", required = true)
  protected String title;
  @XmlElement(name = "Deadline")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar deadline;
  @XmlElement(name = "Enclosures")
  protected Enclosure enclosures;
  @XmlElement(name = "AccessRights")
  protected AccessRightsType accessRights;
  @XmlElement(name = "IntellectualPropertyRights")
  protected IntellectualPropertyRightsType intellectualPropertyRights;
  @XmlElement(name = "NoCopies")
  protected String noCopies;
  @XmlElement(name = "SenderSeriesTitle")
  protected String senderSeriesTitle;
  @XmlElement(name = "SenderFolderTitle")
  protected String senderFolderTitle;
  @XmlElement(name = "SenderVitalRecordIndicator")
  protected Boolean senderVitalRecordIndicator;

  /**
   * Gets the value of the signDate property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getSignDate() {
    return signDate;
  }

  /**
   * Sets the value of the signDate property.
   * 
   * @param value allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setSignDate(XMLGregorianCalendar value) {
    this.signDate = value;
  }

  /**
   * Gets the value of the senderIdentifier property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderIdentifier() {
    return senderIdentifier;
  }

  /**
   * Sets the value of the senderIdentifier property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderIdentifier(String value) {
    this.senderIdentifier = value;
  }

  /**
   * Gets the value of the originalIdentifier property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOriginalIdentifier() {
    return originalIdentifier;
  }

  /**
   * Sets the value of the originalIdentifier property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setOriginalIdentifier(String value) {
    this.originalIdentifier = value;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the languange property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLanguange() {
    return languange;
  }

  /**
   * Sets the value of the languange property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setLanguange(String value) {
    this.languange = value;
  }

  /**
   * Gets the value of the version property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setVersion(String value) {
    this.version = value;
  }

  /**
   * Gets the value of the title property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTitle() {
    return title;
  }

  /**
   * Sets the value of the title property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTitle(String value) {
    this.title = value;
  }

  /**
   * Gets the value of the deadline property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getDeadline() {
    return deadline;
  }

  /**
   * Sets the value of the deadline property.
   * 
   * @param value allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setDeadline(XMLGregorianCalendar value) {
    this.deadline = value;
  }

  /**
   * Gets the value of the enclosures property.
   * 
   * @return possible object is {@link Enclosure }
   * 
   */
  public Enclosure getEnclosures() {
    return enclosures;
  }

  /**
   * Sets the value of the enclosures property.
   * 
   * @param value allowed object is {@link Enclosure }
   * 
   */
  public void setEnclosures(Enclosure value) {
    this.enclosures = value;
  }

  /**
   * Gets the value of the accessRights property.
   * 
   * @return possible object is {@link AccessRightsType }
   * 
   */
  public AccessRightsType getAccessRights() {
    return accessRights;
  }

  /**
   * Sets the value of the accessRights property.
   * 
   * @param value allowed object is {@link AccessRightsType }
   * 
   */
  public void setAccessRights(AccessRightsType value) {
    this.accessRights = value;
  }

  /**
   * Gets the value of the intellectualPropertyRights property.
   * 
   * @return possible object is {@link IntellectualPropertyRightsType }
   * 
   */
  public IntellectualPropertyRightsType getIntellectualPropertyRights() {
    return intellectualPropertyRights;
  }

  /**
   * Sets the value of the intellectualPropertyRights property.
   * 
   * @param value allowed object is {@link IntellectualPropertyRightsType }
   * 
   */
  public void setIntellectualPropertyRights(IntellectualPropertyRightsType value) {
    this.intellectualPropertyRights = value;
  }

  /**
   * Gets the value of the noCopies property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getNoCopies() {
    return noCopies;
  }

  /**
   * Sets the value of the noCopies property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setNoCopies(String value) {
    this.noCopies = value;
  }

  /**
   * Gets the value of the senderSeriesTitle property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderSeriesTitle() {
    return senderSeriesTitle;
  }

  /**
   * Sets the value of the senderSeriesTitle property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderSeriesTitle(String value) {
    this.senderSeriesTitle = value;
  }

  /**
   * Gets the value of the senderFolderTitle property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderFolderTitle() {
    return senderFolderTitle;
  }

  /**
   * Sets the value of the senderFolderTitle property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderFolderTitle(String value) {
    this.senderFolderTitle = value;
  }

  /**
   * Gets the value of the senderVitalRecordIndicator property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isSenderVitalRecordIndicator() {
    return senderVitalRecordIndicator;
  }

  /**
   * Sets the value of the senderVitalRecordIndicator property.
   * 
   * @param value allowed object is {@link Boolean }
   * 
   */
  public void setSenderVitalRecordIndicator(Boolean value) {
    this.senderVitalRecordIndicator = value;
  }

}
