//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the ee.riik.schemas.dhl.rkel_letter package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _LetterExport_QNAME = new QName(
      "http://www.riik.ee/schemas/dhl/rkel_letter", "LetterExport");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: ee.riik.schemas.dhl.rkel_letter
   * 
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link Letter }
   * 
   */
  public Letter createLetter() {
    return new Letter();
  }

  /**
   * Create an instance of {@link Addressee }
   * 
   */
  public Addressee createAddressee() {
    return new Addressee();
  }

  /**
   * Create an instance of {@link Signature }
   * 
   */
  public Signature createSignature() {
    return new Signature();
  }

  /**
   * Create an instance of {@link Compilator }
   * 
   */
  public Compilator createCompilator() {
    return new Compilator();
  }

  /**
   * Create an instance of {@link LetterType }
   * 
   */
  public LetterType createLetterType() {
    return new LetterType();
  }

  /**
   * Create an instance of {@link Enclosure }
   * 
   */
  public Enclosure createEnclosure() {
    return new Enclosure();
  }

  /**
   * Create an instance of {@link AccessRightsType }
   * 
   */
  public AccessRightsType createAccessRightsType() {
    return new AccessRightsType();
  }

  /**
   * Create an instance of {@link SignatureType }
   * 
   */
  public SignatureType createSignatureType() {
    return new SignatureType();
  }

  /**
   * Create an instance of {@link SignatureDataType }
   * 
   */
  public SignatureDataType createSignatureDataType() {
    return new SignatureDataType();
  }

  /**
   * Create an instance of {@link PartyType }
   * 
   */
  public PartyType createPartyType() {
    return new PartyType();
  }

  /**
   * Create an instance of {@link OrganisationType }
   * 
   */
  public OrganisationType createOrganisationType() {
    return new OrganisationType();
  }

  /**
   * Create an instance of {@link PersonType }
   * 
   */
  public PersonType createPersonType() {
    return new PersonType();
  }

  /**
   * Create an instance of {@link IntellectualPropertyRightsType }
   * 
   */
  public IntellectualPropertyRightsType createIntellectualPropertyRightsType() {
    return new IntellectualPropertyRightsType();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link Letter }{@code >}
   * 
   */
  @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl/rkel_letter", name = "LetterExport")
  public JAXBElement<Letter> createLetterExport(Letter value) {
    return new JAXBElement<Letter>(_LetterExport_QNAME, Letter.class, null, value);
  }

}
