//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.riik.ee/schemas/dhl/rkel_letter", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

