//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for PersonType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="jobtitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="telephone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonType", propOrder = {
    "firstname",
    "surname",
    "jobtitle",
    "email",
    "telephone"
})
public class PersonType {

  @XmlElement(required = true)
  protected String firstname;
  @XmlElement(required = true)
  protected String surname;
  protected String jobtitle;
  protected String email;
  protected String telephone;

  /**
   * Gets the value of the firstname property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFirstname() {
    return firstname;
  }

  /**
   * Sets the value of the firstname property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFirstname(String value) {
    this.firstname = value;
  }

  /**
   * Gets the value of the surname property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSurname() {
    return surname;
  }

  /**
   * Sets the value of the surname property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSurname(String value) {
    this.surname = value;
  }

  /**
   * Gets the value of the jobtitle property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getJobtitle() {
    return jobtitle;
  }

  /**
   * Sets the value of the jobtitle property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setJobtitle(String value) {
    this.jobtitle = value;
  }

  /**
   * Gets the value of the email property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEmail() {
    return email;
  }

  /**
   * Sets the value of the email property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setEmail(String value) {
    this.email = value;
  }

  /**
   * Gets the value of the telephone property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTelephone() {
    return telephone;
  }

  /**
   * Sets the value of the telephone property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTelephone(String value) {
    this.telephone = value;
  }

}
