//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:49:24 AM EET 
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl.rkel_letter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Person" type="{http://www.riik.ee/schemas/dhl/rkel_letter}PersonType"/&gt;
 *         &lt;element name="SignatureData" type="{http://www.riik.ee/schemas/dhl/rkel_letter}SignatureDataType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureType", propOrder = {
    "person",
    "signatureData"
})
public class SignatureType {

    @XmlElement(name = "Person", required = true)
    protected PersonType person;
    @XmlElement(name = "SignatureData", required = true)
    protected SignatureDataType signatureData;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the signatureData property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureDataType }
     *     
     */
    public SignatureDataType getSignatureData() {
        return signatureData;
    }

    /**
     * Sets the value of the signatureData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureDataType }
     *     
     */
    public void setSignatureData(SignatureDataType value) {
        this.signatureData = value;
    }

}
