//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dokumendi transpordiaadress
 * 
 * <p>
 * Java class for aadressType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aadressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}regnr" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}isikukood" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}ametikoha_kood" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}ametikoha_nimetus" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}allyksuse_kood" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}allyksuse_nimetus" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}epost" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}nimi" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}asutuse_nimi" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}osakonna_kood" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}osakonna_nimi" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aadressType", propOrder = {

    })
public class AadressType {

  protected String regnr;
  protected String isikukood;
  @XmlElement(name = "ametikoha_kood")
  protected BigInteger ametikohaKood;
  @XmlElement(name = "ametikoha_nimetus")
  protected BigInteger ametikohaNimetus;
  @XmlElement(name = "allyksuse_kood")
  protected BigInteger allyksuseKood;
  @XmlElement(name = "allyksuse_nimetus")
  protected BigInteger allyksuseNimetus;
  protected String epost;
  protected String nimi;
  @XmlElement(name = "asutuse_nimi")
  protected String asutuseNimi;
  @XmlElement(name = "osakonna_kood")
  protected String osakonnaKood;
  @XmlElement(name = "osakonna_nimi")
  protected String osakonnaNimi;

  /**
   * Gets the value of the regnr property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRegnr() {
    return regnr;
  }

  /**
   * Sets the value of the regnr property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRegnr(String value) {
    this.regnr = value;
  }

  /**
   * Gets the value of the isikukood property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getIsikukood() {
    return isikukood;
  }

  /**
   * Sets the value of the isikukood property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setIsikukood(String value) {
    this.isikukood = value;
  }

  /**
   * Gets the value of the ametikohaKood property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getAmetikohaKood() {
    return ametikohaKood;
  }

  /**
   * Sets the value of the ametikohaKood property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setAmetikohaKood(BigInteger value) {
    this.ametikohaKood = value;
  }

  /**
   * Gets the value of the ametikohaNimetus property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getAmetikohaNimetus() {
    return ametikohaNimetus;
  }

  /**
   * Sets the value of the ametikohaNimetus property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setAmetikohaNimetus(BigInteger value) {
    this.ametikohaNimetus = value;
  }

  /**
   * Gets the value of the allyksuseKood property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getAllyksuseKood() {
    return allyksuseKood;
  }

  /**
   * Sets the value of the allyksuseKood property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setAllyksuseKood(BigInteger value) {
    this.allyksuseKood = value;
  }

  /**
   * Gets the value of the allyksuseNimetus property.
   * 
   * @return possible object is {@link BigInteger }
   * 
   */
  public BigInteger getAllyksuseNimetus() {
    return allyksuseNimetus;
  }

  /**
   * Sets the value of the allyksuseNimetus property.
   * 
   * @param value allowed object is {@link BigInteger }
   * 
   */
  public void setAllyksuseNimetus(BigInteger value) {
    this.allyksuseNimetus = value;
  }

  /**
   * Gets the value of the epost property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEpost() {
    return epost;
  }

  /**
   * Sets the value of the epost property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setEpost(String value) {
    this.epost = value;
  }

  /**
   * Gets the value of the nimi property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getNimi() {
    return nimi;
  }

  /**
   * Sets the value of the nimi property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setNimi(String value) {
    this.nimi = value;
  }

  /**
   * Gets the value of the asutuseNimi property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getAsutuseNimi() {
    return asutuseNimi;
  }

  /**
   * Sets the value of the asutuseNimi property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setAsutuseNimi(String value) {
    this.asutuseNimi = value;
  }

  /**
   * Gets the value of the osakonnaKood property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOsakonnaKood() {
    return osakonnaKood;
  }

  /**
   * Sets the value of the osakonnaKood property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setOsakonnaKood(String value) {
    this.osakonnaKood = value;
  }

  /**
   * Gets the value of the osakonnaNimi property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getOsakonnaNimi() {
    return osakonnaNimi;
  }

  /**
   * Sets the value of the osakonnaNimi property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setOsakonnaNimi(String value) {
    this.osakonnaNimi = value;
  }

}
