//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:49:24 AM EET 
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}transport"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}metaxml"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportAndMetaxml"
})
@XmlRootElement(name = "ajalugu")
public class Ajalugu {

    @XmlElements({
        @XmlElement(name = "transport", type = Transport.class),
        @XmlElement(name = "metaxml", type = Metaxml.class)
    })
    protected List<Object> transportAndMetaxml;

    /**
     * Gets the value of the transportAndMetaxml property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportAndMetaxml property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportAndMetaxml().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transport }
     * {@link Metaxml }
     * 
     * 
     */
    public List<Object> getTransportAndMetaxml() {
        if (transportAndMetaxml == null) {
            transportAndMetaxml = new ArrayList<Object>();
        }
        return this.transportAndMetaxml;
    }

}
