//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.17 at 11:49:24 AM EET 
//


package ee.ria.dhx.server.types.ee.riik.schemas.dhl;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ee.riik.schemas.dhl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Regnr_QNAME = new QName("http://www.riik.ee/schemas/dhl", "regnr");
    private final static QName _Isikukood_QNAME = new QName("http://www.riik.ee/schemas/dhl", "isikukood");
    private final static QName _AmetikohaKood_QNAME = new QName("http://www.riik.ee/schemas/dhl", "ametikoha_kood");
    private final static QName _AmetikohaNimetus_QNAME = new QName("http://www.riik.ee/schemas/dhl", "ametikoha_nimetus");
    private final static QName _AllyksuseKood_QNAME = new QName("http://www.riik.ee/schemas/dhl", "allyksuse_kood");
    private final static QName _AllyksuseNimetus_QNAME = new QName("http://www.riik.ee/schemas/dhl", "allyksuse_nimetus");
    private final static QName _Epost_QNAME = new QName("http://www.riik.ee/schemas/dhl", "epost");
    private final static QName _Nimi_QNAME = new QName("http://www.riik.ee/schemas/dhl", "nimi");
    private final static QName _AsutuseNimi_QNAME = new QName("http://www.riik.ee/schemas/dhl", "asutuse_nimi");
    private final static QName _OsakonnaKood_QNAME = new QName("http://www.riik.ee/schemas/dhl", "osakonna_kood");
    private final static QName _OsakonnaNimi_QNAME = new QName("http://www.riik.ee/schemas/dhl", "osakonna_nimi");
    private final static QName _Saatja_QNAME = new QName("http://www.riik.ee/schemas/dhl", "saatja");
    private final static QName _Saaja_QNAME = new QName("http://www.riik.ee/schemas/dhl", "saaja");
    private final static QName _Vahendaja_QNAME = new QName("http://www.riik.ee/schemas/dhl", "vahendaja");
    private final static QName _Dokument_QNAME = new QName("http://www.riik.ee/schemas/dhl", "dokument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ee.riik.schemas.dhl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Edastus }
     * 
     */
    public Edastus createEdastus() {
        return new Edastus();
    }

    /**
     * Create an instance of {@link DhlDokumentType }
     * 
     */
    public DhlDokumentType createDhlDokumentType() {
        return new DhlDokumentType();
    }

    /**
     * Create an instance of {@link AadressType }
     * 
     */
    public AadressType createAadressType() {
        return new AadressType();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link Edastus.Metaxml }
     * 
     */
    public Edastus.Metaxml createEdastusMetaxml() {
        return new Edastus.Metaxml();
    }

    /**
     * Create an instance of {@link Transport }
     * 
     */
    public Transport createTransport() {
        return new Transport();
    }

    /**
     * Create an instance of {@link  ee.ria.dhx.server.types.ee.riik.schemas.dhl.Metaxml }
     * 
     */
    public ee.ria.dhx.server.types.ee.riik.schemas.dhl.Metaxml createMetaxml() {
        return new ee.ria.dhx.server.types.ee.riik.schemas.dhl.Metaxml();
    }

    /**
     * Create an instance of {@link Ajalugu }
     * 
     */
    public Ajalugu createAjalugu() {
        return new Ajalugu();
    }

    /**
     * Create an instance of {@link TagasisideType }
     * 
     */
    public TagasisideType createTagasisideType() {
        return new TagasisideType();
    }

    /**
     * Create an instance of {@link DhlDokumentType.Ref }
     * 
     */
    public DhlDokumentType.Ref createDhlDokumentTypeRef() {
        return new DhlDokumentType.Ref();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "regnr")
    public JAXBElement<String> createRegnr(String value) {
        return new JAXBElement<String>(_Regnr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "isikukood")
    public JAXBElement<String> createIsikukood(String value) {
        return new JAXBElement<String>(_Isikukood_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "ametikoha_kood")
    public JAXBElement<BigInteger> createAmetikohaKood(BigInteger value) {
        return new JAXBElement<BigInteger>(_AmetikohaKood_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "ametikoha_nimetus")
    public JAXBElement<BigInteger> createAmetikohaNimetus(BigInteger value) {
        return new JAXBElement<BigInteger>(_AmetikohaNimetus_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "allyksuse_kood")
    public JAXBElement<BigInteger> createAllyksuseKood(BigInteger value) {
        return new JAXBElement<BigInteger>(_AllyksuseKood_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "allyksuse_nimetus")
    public JAXBElement<BigInteger> createAllyksuseNimetus(BigInteger value) {
        return new JAXBElement<BigInteger>(_AllyksuseNimetus_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "epost")
    public JAXBElement<String> createEpost(String value) {
        return new JAXBElement<String>(_Epost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "nimi")
    public JAXBElement<String> createNimi(String value) {
        return new JAXBElement<String>(_Nimi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "asutuse_nimi")
    public JAXBElement<String> createAsutuseNimi(String value) {
        return new JAXBElement<String>(_AsutuseNimi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "osakonna_kood")
    public JAXBElement<String> createOsakonnaKood(String value) {
        return new JAXBElement<String>(_OsakonnaKood_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "osakonna_nimi")
    public JAXBElement<String> createOsakonnaNimi(String value) {
        return new JAXBElement<String>(_OsakonnaNimi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AadressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "saatja")
    public JAXBElement<AadressType> createSaatja(AadressType value) {
        return new JAXBElement<AadressType>(_Saatja_QNAME, AadressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AadressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "saaja")
    public JAXBElement<AadressType> createSaaja(AadressType value) {
        return new JAXBElement<AadressType>(_Saaja_QNAME, AadressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AadressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "vahendaja")
    public JAXBElement<AadressType> createVahendaja(AadressType value) {
        return new JAXBElement<AadressType>(_Vahendaja_QNAME, AadressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DhlDokumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.riik.ee/schemas/dhl", name = "dokument")
    public JAXBElement<DhlDokumentType> createDokument(DhlDokumentType value) {
        return new JAXBElement<DhlDokumentType>(_Dokument_QNAME, DhlDokumentType.class, null, value);
    }

}
