//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.14 at 09:18:04 PM EET 
//


package ee.riik.schemas.dhl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}saatja" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}saaja" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.riik.ee/schemas/dhl}vahendaja" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "saatja",
    "saaja",
    "vahendaja"
})
@XmlRootElement(name = "transport")
public class Transport {

    protected AadressType saatja;
    protected List<AadressType> saaja;
    protected AadressType vahendaja;

    /**
     * Gets the value of the saatja property.
     * 
     * @return
     *     possible object is
     *     {@link AadressType }
     *     
     */
    public AadressType getSaatja() {
        return saatja;
    }

    /**
     * Sets the value of the saatja property.
     * 
     * @param value
     *     allowed object is
     *     {@link AadressType }
     *     
     */
    public void setSaatja(AadressType value) {
        this.saatja = value;
    }

    /**
     * Gets the value of the saaja property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saaja property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSaaja().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AadressType }
     * 
     * 
     */
    public List<AadressType> getSaaja() {
        if (saaja == null) {
            saaja = new ArrayList<AadressType>();
        }
        return this.saaja;
    }

    /**
     * Gets the value of the vahendaja property.
     * 
     * @return
     *     possible object is
     *     {@link AadressType }
     *     
     */
    public AadressType getVahendaja() {
        return vahendaja;
    }

    /**
     * Sets the value of the vahendaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link AadressType }
     *     
     */
    public void setVahendaja(AadressType value) {
        this.vahendaja = value;
    }

}
