//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.17 at 11:49:24 AM EET
//


package ee.ria.dhx.server.types.ee.sk.digidoc.v1_3;

import ee.ria.dhx.server.types.org.w3._2000._09.xmldsig_.SignatureType;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for SignedDocType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignedDocType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DataFile" type="{http://www.sk.ee/DigiDoc/v1.3.0#}DataFileType" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" fixed="DIGIDOC-XML" /&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.3" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignedDocType", propOrder = {
    "dataFile",
    "signature"
})
public class SignedDocType {

  @XmlElement(name = "DataFile", required = true)
  protected List<DataFileType> dataFile;
  @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
  protected List<SignatureType> signature;
  @XmlAttribute(name = "format")
  protected String format;
  @XmlAttribute(name = "version")
  protected String version;

  /**
   * Gets the value of the dataFile property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the dataFile property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getDataFile().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link DataFileType }
   * 
   * @return list of {@link DataFileType}
   */
  public List<DataFileType> getDataFile() {
    if (dataFile == null) {
      dataFile = new ArrayList<DataFileType>();
    }
    return this.dataFile;
  }

  /**
   * Gets the value of the signature property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the signature property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getSignature().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link SignatureType }
   * 
   * @return list of {@link SignatureType}
   */
  public List<SignatureType> getSignature() {
    if (signature == null) {
      signature = new ArrayList<SignatureType>();
    }
    return this.signature;
  }

  /**
   * Gets the value of the format property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getFormat() {
    if (format == null) {
      return "DIGIDOC-XML";
    } else {
      return format;
    }
  }

  /**
   * Sets the value of the format property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setFormat(String value) {
    this.format = value;
  }

  /**
   * Gets the value of the version property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getVersion() {
    if (version == null) {
      return "1.3";
    } else {
      return version;
    }
  }

  /**
   * Sets the value of the version property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setVersion(String value) {
    this.version = value;
  }

}
