//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.11.10 at 01:13:12 PM EET
//


package ee.ria.dhx.types.eu.x_road.xsd.identifiers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the eu.x_road.xsd.identifiers package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _XRoadInstance_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "xRoadInstance");
  private final static QName _MemberClass_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "memberClass");
  private final static QName _MemberCode_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "memberCode");
  private final static QName _SubsystemCode_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "subsystemCode");
  private final static QName _GroupCode_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "groupCode");
  private final static QName _ServiceCode_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "serviceCode");
  private final static QName _ServiceVersion_QNAME = new QName(
      "http://x-road.eu/xsd/identifiers", "serviceVersion");
  private final static QName _SecurityCategoryCode_QNAME = new QName(
      "http://x-road.eu/xsd/identifiers", "securityCategoryCode");
  private final static QName _ServerCode_QNAME = new QName("http://x-road.eu/xsd/identifiers",
      "serverCode");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: eu.x_road.xsd.identifiers
   * 
   */
  public ObjectFactory() {}

  /**
   * Create an instance of {@link XRoadClientIdentifierType }
   * 
   * @return created object
   */
  public XRoadClientIdentifierType createXRoadClientIdentifierType() {
    return new XRoadClientIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadServiceIdentifierType }
   * 
   * @return created object
   */
  public XRoadServiceIdentifierType createXRoadServiceIdentifierType() {
    return new XRoadServiceIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadCentralServiceIdentifierType }
   * 
   * @return created object
   */
  public XRoadCentralServiceIdentifierType createXRoadCentralServiceIdentifierType() {
    return new XRoadCentralServiceIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadIdentifierType }
   * 
   * @return created object
   */
  public XRoadIdentifierType createXRoadIdentifierType() {
    return new XRoadIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadSecurityCategoryIdentifierType }
   * 
   * @return created object
   */
  public XRoadSecurityCategoryIdentifierType createXRoadSecurityCategoryIdentifierType() {
    return new XRoadSecurityCategoryIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadSecurityServerIdentifierType }
   * 
   * @return created object
   */
  public XRoadSecurityServerIdentifierType createXRoadSecurityServerIdentifierType() {
    return new XRoadSecurityServerIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadGlobalGroupIdentifierType }
   * 
   * @return created object
   */
  public XRoadGlobalGroupIdentifierType createXRoadGlobalGroupIdentifierType() {
    return new XRoadGlobalGroupIdentifierType();
  }

  /**
   * Create an instance of {@link XRoadLocalGroupIdentifierType }
   * 
   * @return created object
   */
  public XRoadLocalGroupIdentifierType createXRoadLocalGroupIdentifierType() {
    return new XRoadLocalGroupIdentifierType();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "xRoadInstance")
  public JAXBElement<String> createXRoadInstance(String value) {
    return new JAXBElement<String>(_XRoadInstance_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "memberClass")
  public JAXBElement<String> createMemberClass(String value) {
    return new JAXBElement<String>(_MemberClass_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "memberCode")
  public JAXBElement<String> createMemberCode(String value) {
    return new JAXBElement<String>(_MemberCode_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "subsystemCode")
  public JAXBElement<String> createSubsystemCode(String value) {
    return new JAXBElement<String>(_SubsystemCode_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "groupCode")
  public JAXBElement<String> createGroupCode(String value) {
    return new JAXBElement<String>(_GroupCode_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "serviceCode")
  public JAXBElement<String> createServiceCode(String value) {
    return new JAXBElement<String>(_ServiceCode_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "serviceVersion")
  public JAXBElement<String> createServiceVersion(String value) {
    return new JAXBElement<String>(_ServiceVersion_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "securityCategoryCode")
  public JAXBElement<String> createSecurityCategoryCode(String value) {
    return new JAXBElement<String>(_SecurityCategoryCode_QNAME, String.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
   * 
   * @param value value
   * @return created object
   */
  @XmlElementDecl(namespace = "http://x-road.eu/xsd/identifiers", name = "serverCode")
  public JAXBElement<String> createServerCode(String value) {
    return new JAXBElement<String>(_ServerCode_QNAME, String.class, null, value);
  }

}
